import type { Artifact } from "./types";

export const bathroom: Artifact[] = [
  {
    slug: "bathroom",
    name: "Bathroom",
    what: "A room where humans wash and dispose of bodily waste.",
    why: "Waste and unwashed skin both carry pathogens. Containing waste disposal and washing to one plumbed room keeps disease from spreading through the rest of the home.",
    has: ["toilet", "shower", "bathtub", "sink", "mirror", "bath mat", "towel", "towel bar", "medicine cabinet", "toothbrush", "shower curtain", "toilet paper holder", "bathroom scale"],
  },
  {
    slug: "toilet",
    name: "Toilet",
    what: "A plumbed fixture for disposing of bodily waste with water.",
    why: "Waste carries pathogens and needs to be sealed away and flushed out of living space, not left exposed where it can spread disease.",
    has: ["bowl", "tank", "seat"],
  },
  {
    slug: "bowl",
    name: "Bowl",
    what: "The water-holding basin of a toilet that receives waste.",
    why: "Standing water in the bowl seals the pipe below it, blocking sewer gas and odor from rising back up into the room.",
    has: ["ceramic"],
  },
  {
    slug: "tank",
    name: "Tank",
    what: "A reservoir that holds water for flushing a toilet.",
    why: "A flush needs a sudden volume of water to clear the bowl and refill its seal. The tank stores that volume, ready to release on demand.",
    has: ["ceramic", "flush valve"],
  },
  {
    slug: "flush-valve",
    name: "Flush Valve",
    what: "A valve at the bottom of a toilet tank that opens to release its stored water into the bowl at once.",
    why: "The tank's whole volume of water has to release almost instantly for the flush to have enough force to clear the bowl in a single motion.",
    has: [],
  },
  {
    slug: "seat",
    name: "Seat",
    what: "The ring humans sit on, hinged to a toilet bowl.",
    why: "It raises and shapes the contact surface for comfort and hygiene, and lifts away for cleaning or alternate use.",
    has: ["polymer", "hinges"],
  },
  {
    slug: "shower",
    name: "Shower",
    what: "A fixture that sprays water over the body for washing.",
    why: "Skin builds up oil, sweat, and bacteria over the day. Regular washing removes that buildup, preventing infection, irritation, and odor.",
    has: ["showerhead", "drain", "faucet"],
  },
  {
    slug: "showerhead",
    name: "Showerhead",
    what: "The perforated fixture that turns a water stream into a spray of droplets.",
    why: "A single solid stream wouldn't cover the whole body. Splitting it into many small streams spreads coverage and softens the impact on skin.",
    has: ["nozzles"],
  },
  {
    slug: "nozzles",
    name: "Nozzles",
    what: "Small individual openings that each shape water into a single narrow stream.",
    why: "Many small streams cover far more surface area evenly than one single wide stream would at the same water pressure.",
    has: [],
  },
  {
    slug: "bathtub",
    name: "Bathtub",
    what: "A fixed basin built into a bathroom floor that a person sits or lies in, filled with water for washing or soaking.",
    why: "A shower rinses the body but doesn't let water pool around it — full immersion loosens muscles and soaks off dirt in a way a standing spray can't, and it's the only safe way to bathe an infant or anyone who can't stand unsupported.",
    has: ["tub", "faucet", "drain"],
  },
  {
    slug: "tub",
    name: "Tub",
    what: "The deep, sealed basin shell of a bathtub that holds standing water around a submerged body.",
    why: "It has to hold several inches of standing water pooled around a body without leaking or draining right away, unlike a sink or shower basin built to channel water straight through.",
    has: ["ceramic"],
  },
  {
    slug: "sink",
    name: "Sink",
    what: "A basin with running water for washing hands and face.",
    why: "Hands touch many surfaces and pick up germs constantly. Frequent, quick washing breaks the chain of transmission before it reaches food or the face.",
    has: ["basin", "faucet", "drain"],
  },
  {
    slug: "basin",
    name: "Basin",
    what: "The bowl-shaped fixture that holds and channels water while washing.",
    why: "Without a contained basin, washing at a faucet would just splash water everywhere instead of channeling it straight to the drain.",
    has: ["ceramic"],
  },
  {
    slug: "mirror",
    name: "Mirror",
    what: "A flat panel of glass with a reflective coating on its back, mounted on a bathroom wall to show a person's reflection.",
    why: "Shaving, brushing teeth, and grooming all need visual feedback on your own face and body that no other fixture in the room provides.",
    has: ["glass", "reflective coating", "mirror frame"],
  },
  {
    slug: "reflective-coating",
    name: "Reflective Coating",
    what: "A thin layer of metal, usually aluminum or silver, deposited on the back of a sheet of glass.",
    why: "Glass alone just lets light through. The metal layer behind it is what actually bounces that light back, turning a clear pane into a reflective one.",
    has: [],
  },
  {
    slug: "mirror-frame",
    name: "Mirror Frame",
    what: "The rigid border around a mirror's glass that holds it in place and protects its edges.",
    why: "A bare sheet of glass has sharp, unprotected edges and no way to mount to a wall. The frame secures the glass and gives it a clean edge to hang from.",
    has: ["wood"],
  },
  {
    slug: "bath-mat",
    name: "Bath Mat",
    what: "An absorbent mat placed on the floor beside a shower or tub to catch water and provide traction.",
    why: "Wet feet on hard tile is a slipping hazard, and dripped water pools straight onto the floor. A mat soaks it up and gives a stable, non-slip step out of the shower.",
    has: ["fabric", "rubber"],
  },
  {
    slug: "towel",
    name: "Towel",
    what: "An absorbent fabric sheet used to dry the body after washing.",
    why: "Skin left wet after a shower stays cold and leaves damp marks on clothing — a towel wicks that surface water away fast enough to dry off before getting dressed.",
    has: ["fabric"],
  },
  {
    slug: "towel-bar",
    name: "Towel Bar",
    what: "A wall-mounted horizontal bar for hanging a towel to dry between uses.",
    why: "A damp towel left balled up on a hook or the floor stays wet and starts to smell — draped flat over a bar it dries fully before it's needed again.",
    has: ["steel"],
  },
  {
    slug: "medicine-cabinet",
    name: "Medicine Cabinet",
    what: "A small mirrored cabinet mounted above a bathroom sink for storing medicine and toiletries.",
    why: "Medicine and toiletries need to be kept close to the sink where they're used and off the counter — mounting the cabinet's door as a mirror means it does double duty as the room's mirror instead of needing a separate one nearby.",
    has: ["medicine cabinet shelves", "mirror"],
  },
  {
    slug: "medicine-cabinet-shelves",
    name: "Medicine Cabinet Shelves",
    what: "Thin fixed glass shelves inside a medicine cabinet's shallow wall-mounted box.",
    why: "Small bottles and containers need to stand upright without toppling into each other — individual shelves hold rows of them separated instead of piled loose in a drawer.",
    has: ["glass"],
  },
  {
    slug: "toothbrush",
    name: "Toothbrush",
    what: "A small handheld brush with a nylon-bristled head, used to clean teeth.",
    why: "Food particles and bacteria build a sticky film on teeth throughout the day — brushing physically scrubs that film off before it hardens into plaque and causes decay or gum disease.",
    has: ["bristles", "polymer"],
  },
  {
    slug: "bristles",
    name: "Bristles",
    what: "Short, stiff nylon filaments packed into a toothbrush's head.",
    why: "Their fine, flexible tips reach into the narrow gaps between teeth and along the gumline that a flat or sponge surface couldn't scrub effectively.",
    has: ["polymer"],
  },
  {
    slug: "shower-curtain",
    name: "Shower Curtain",
    what: "A waterproof fabric or plastic sheet hung around a shower or tub to contain splashing water.",
    why: "An open shower would spray water across the bathroom floor with every use — a curtain drawn around the wet area keeps that spray contained to the tub or shower pan.",
    has: ["shower curtain rings", "curtain rod", "polymer"],
  },
  {
    slug: "shower-curtain-rings",
    name: "Shower Curtain Rings",
    what: "Small rings clipped through a shower curtain's top edge that slide along a rod.",
    why: "The curtain needs to slide open and closed along the rod repeatedly without tearing — rings distribute that sliding friction onto a durable loop instead of a worn fabric grommet.",
    has: ["steel"],
  },
  {
    slug: "toilet-paper-holder",
    name: "Toilet Paper Holder",
    what: "A wall-mounted bracket that holds a roll of toilet paper within reach of the toilet.",
    why: "A roll set loose on the floor or counter unspools messily and gets wet — a fixed holder keeps it spinning cleanly on an axle right where it's needed.",
    has: ["holder rod", "wall bracket"],
  },
  {
    slug: "holder-rod",
    name: "Holder Rod",
    what: "A thin spring-loaded rod that threads through a toilet paper roll's core and lets it spin freely.",
    why: "The roll has to spin freely so paper pulls off cleanly with one hand — a rod through its core is what lets it rotate instead of just sliding or crumpling.",
    has: ["steel"],
  },
  {
    slug: "wall-bracket",
    name: "Wall Bracket",
    what: "The two mounted end pieces that hold a toilet paper holder's rod fixed to the wall.",
    why: "The rod alone would fall the moment weight is pulled on the paper — brackets anchor it firmly to the wall so pulling paper doesn't yank the whole thing down.",
    has: ["steel"],
  },
  {
    slug: "bathroom-scale",
    name: "Bathroom Scale",
    what: "A flat platform with an internal sensor that measures a person's body weight when they stand on it.",
    why: "Body weight changes gradually and isn't something a person can judge by feel — a scale gives an exact, repeatable number to track that change over time.",
    has: ["load sensor", "display"],
  },
  {
    slug: "load-sensor",
    name: "Load Sensor",
    what: "A small strain gauge inside a scale that flexes slightly under weight and converts that flex into an electrical signal.",
    why: "Weight needs to be converted into a number a display can read — the sensor's tiny, precise flex under load is what translates physical force into that measurable electrical signal.",
    has: ["steel"],
  },
];
