import type { Artifact } from "./types";

export const bedroom: Artifact[] = [
  {
    slug: "bedroom",
    name: "Bedroom",
    what: "A room where humans sleep and rest.",
    why: "The body and brain need extended, uninterrupted downtime to repair tissue and consolidate memory. A dark, quiet, enclosed space makes that rest possible.",
    has: ["bed", "closet", "lamp", "nightstand", "curtains"],
  },
  {
    slug: "bed",
    name: "Bed",
    what: "A raised, padded surface for lying down and sleeping.",
    why: "Sleeping on bare ground is cold, hard, and uneven, which disturbs sleep and strains joints. Elevation and padding regulate body temperature and cushion pressure points.",
    has: ["mattress", "frame", "pillow"],
  },
  {
    slug: "mattress",
    name: "Mattress",
    what: "A thick, padded cushion filled with foam, springs, or fiber that a person lies on.",
    why: "A bare frame or floor is too hard for sustained contact. Padding spreads body weight evenly, reducing pressure on hips and shoulders so muscles can fully relax.",
    has: ["foam", "cover"],
  },
  {
    slug: "foam",
    name: "Foam",
    what: "A soft, porous material that compresses under weight and springs back.",
    why: "Rigid material would push back evenly hard everywhere. Foam yields more where weight is greatest, letting it cushion hips and shoulders differently from lighter contact points.",
    has: ["polymer", "air cells"],
  },
  {
    slug: "air-cells",
    name: "Air Cells",
    what: "Tiny pockets of trapped air spread throughout the foam.",
    why: "Air compresses easily, so the cells absorb impact instead of pushing straight back. They also let air move through the foam so heat and moisture don't get trapped against the body.",
    has: ["cell wall", "trapped air"],
  },
  {
    slug: "cell-wall",
    name: "Cell Wall",
    what: "A thin membrane of foam material surrounding each air pocket.",
    why: "It holds each pocket's shape and keeps neighboring cells separate, so pressure in one cell doesn't just leak straight into the next when the foam is compressed.",
    has: [],
  },
  {
    slug: "trapped-air",
    name: "Trapped Air",
    what: "Air sealed inside a cell when the foam was formed.",
    why: "Air resists compression but escapes slowly through the cell walls under pressure. That slow leak-and-refill is what gives foam its gradual give-and-recover feel instead of an instant bounce.",
    has: [],
  },
  {
    slug: "cover",
    name: "Cover",
    what: "A removable fabric layer wrapped around the mattress.",
    why: "The mattress itself absorbs sweat, oil, and dust and can't be washed. A removable cover can be stripped off and cleaned without damaging the foam underneath.",
    has: ["fabric", "stitching"],
  },
  {
    slug: "frame",
    name: "Bed Frame",
    what: "A rigid structure that holds the mattress up off the floor.",
    why: "The floor is cold, drafty, and collects dust and pests. Raising the mattress keeps the sleeper warmer and the sleeping surface cleaner.",
    has: ["legs", "rails"],
  },
  {
    slug: "pillow",
    name: "Pillow",
    what: "A small, soft cushion for supporting the head and neck.",
    why: "Without support, the head tilts and strains the neck and upper spine overnight. A pillow keeps the spine aligned so muscles aren't working while asleep.",
    has: ["filling", "case"],
  },
  {
    slug: "closet",
    name: "Closet",
    what: "An enclosed storage space for clothing.",
    why: "Clothes need to be kept clean, uncrumpled, and out of the way, while still being quick to find and reach for daily.",
    has: ["rod", "closet shelves", "door"],
  },
  {
    slug: "lamp",
    name: "Lamp",
    what: "A portable or fixed source of artificial light.",
    why: "Human eyes can't see without light, and natural light disappears at night. Artificial light lets people keep doing things after the sun sets.",
    has: ["bulb", "shade", "switch"],
  },
  {
    slug: "legs",
    name: "Legs",
    what: "The vertical supports that raise a frame off the floor.",
    why: "Without legs, a frame would sit flush on the ground, defeating the point of raising the mattress away from the cold, drafty floor.",
    has: ["wood"],
  },
  {
    slug: "rails",
    name: "Rails",
    what: "The horizontal side pieces connecting a frame's ends and supporting the mattress's edges.",
    why: "Without rails, the mattress would sag unsupported along its long sides instead of being held flat and level.",
    has: ["wood"],
  },
  {
    slug: "filling",
    name: "Filling",
    what: "The soft material packed inside a pillow — foam, down, or fiber.",
    why: "It's what actually molds to the shape of the head and neck; without it, the pillow would just be a flat, empty shell offering no support.",
    has: ["down", "fiberfill"],
  },
  {
    slug: "case",
    name: "Case",
    what: "A removable fabric cover around a pillow.",
    why: "Like a mattress cover, it catches oil, sweat, and dust so it can be washed regularly without exposing or wearing out the filling underneath.",
    has: ["fabric", "zipper"],
  },
  {
    slug: "rod",
    name: "Rod",
    what: "A horizontal bar for hanging clothes on hangers.",
    why: "Hanging keeps clothes from creasing the way folding and stacking does, and keeps each item visible and reachable at a glance.",
    has: ["steel"],
  },
  {
    slug: "closet-shelves",
    name: "Closet Shelves",
    what: "Fixed platforms above or beside a closet's hanging rod, for folded items.",
    why: "Not everything hangs well — sweaters and stacks of folded clothing need a flat surface instead of a bar, or they lose their shape.",
    has: ["wood"],
  },
  {
    slug: "door",
    name: "Door",
    what: "A panel that closes off an opening.",
    why: "It keeps what's behind it out of sight and out of the room's dust and light, which would otherwise fade fabric or let clutter spill into the room.",
    has: ["wood", "hinges"],
  },
  {
    slug: "bulb",
    name: "Bulb",
    what: "The component that converts electricity into visible light.",
    why: "It's the actual light source — everything else in a lamp exists just to hold it, power it, or direct where its light goes.",
    has: ["filament", "glass"],
  },
  {
    slug: "shade",
    name: "Shade",
    what: "A cover around a bulb that diffuses and directs its light.",
    why: "A bare bulb glares directly into the eyes. A shade spreads that light out and points it toward where it's actually useful.",
    has: ["fabric", "wire"],
  },
  {
    slug: "switch",
    name: "Switch",
    what: "A mechanism that opens or closes the circuit powering a device.",
    why: "Without a switch, a lamp would either always be off or always be on, wasting power or forcing it to be unplugged just to turn off.",
    has: ["contacts", "spring"],
  },
  {
    slug: "stitching",
    name: "Stitching",
    what: "Thread sewn through fabric in a repeating pattern to join two edges together.",
    why: "Fabric alone doesn't hold a shape. Stitching is what turns loose panels of cloth into a fitted, structural cover that stays together under regular use.",
    has: [],
  },
  {
    slug: "down",
    name: "Down",
    what: "The soft, fine layer of feathers found underneath a bird's outer feathers.",
    why: "Its clustered, branching structure traps air in tiny pockets, which is what actually insulates and cushions — the down itself is just the frame holding that air in place.",
    has: [],
  },
  {
    slug: "fiberfill",
    name: "Fiberfill",
    what: "Synthetic fibers, often polyester, crimped and clustered to mimic down.",
    why: "It gives similar loft and cushioning to down without the cost or allergy risk, though it compresses and loses its shape faster over repeated use.",
    has: [],
  },
  {
    slug: "zipper",
    name: "Zipper",
    what: "Two rows of interlocking teeth drawn together by a sliding pull.",
    why: "It lets a case be opened fully to remove and wash what's inside, then resealed just as fast — something permanent stitching alone can't do reversibly.",
    has: [],
  },
  {
    slug: "filament",
    name: "Filament",
    what: "A thin wire, usually tungsten, that glows white-hot when current passes through it.",
    why: "Resistance in the thin wire converts electrical energy directly into heat and light. Tungsten is used because it can reach that heat without melting.",
    has: [],
  },
  {
    slug: "contacts",
    name: "Contacts",
    what: "Two conductive metal points that touch to complete a circuit or separate to break it.",
    why: "Physically joining or separating two contacts is the simplest, most reliable way to start and stop the flow of electricity on demand.",
    has: [],
  },
  {
    slug: "spring",
    name: "Spring",
    what: "A coiled piece of metal that stores energy when bent and releases it to snap back to shape.",
    why: "It gives a switch or button a decisive, self-resetting click, so it returns to its resting position on its own instead of staying wherever it was pushed.",
    has: [],
  },
  {
    slug: "nightstand",
    name: "Nightstand",
    what: "A small table set beside a bed, within arm's reach of where a person sleeps.",
    why: "A lamp, glasses, phone, or a book needs a surface next to the bed. Reaching across a dark room to find them defeats the point of having them nearby.",
    has: ["drawer", "wood"],
  },
  {
    slug: "drawer",
    name: "Drawer",
    what: "A boxed compartment that slides in and out of a piece of furniture on a track.",
    why: "Small items like glasses or a charger need to be kept out of sight and off the surface, but still within arm's reach. A drawer gives enclosed storage that opens in one motion.",
    has: ["wood", "drawer slide"],
  },
  {
    slug: "drawer-slide",
    name: "Drawer Slide",
    what: "A metal track fixed to a drawer and its cabinet that lets the drawer glide straight in and out.",
    why: "Without a track, a drawer would rock, jam, or need to be lifted fully out rather than sliding smoothly on centered rails.",
    has: [],
  },
  {
    slug: "curtains",
    name: "Curtains",
    what: "A fabric panel hung over a window that can be drawn to block or filter outside light.",
    why: "A bedroom needs to go dark on demand for sleep, but sunlight and streetlights come through a window regardless of the hour. Curtains are what actually lets the room block that light out.",
    has: ["fabric", "curtain rod"],
  },
  {
    slug: "curtain-rod",
    name: "Curtain Rod",
    what: "A horizontal bar mounted above a window that curtain fabric hangs from and slides along.",
    why: "Curtains need to slide open and closed in one motion, not be unhooked and remounted each time — the rod is what lets the fabric glide side to side along a fixed track.",
    has: ["steel"],
  },
];
