import type { Artifact } from "./types";

export const garage: Artifact[] = [
  {
    slug: "garage",
    name: "Garage",
    what: "A room or structure attached to or near a house where a car is parked and tools are stored.",
    why: "A car left outside is exposed to weather, theft, and temperature swings that degrade paint, batteries, and fluids. An enclosed space also gives a dedicated spot for tools and yard equipment that don't belong inside the living space.",
    has: ["garage door", "workbench", "garage shelving", "toolbox", "car", "lawnmower", "extension cord", "ladder", "fire extinguisher"],
  },
  {
    slug: "garage-door",
    name: "Garage Door",
    what: "A large, sectioned door that rolls or tilts up along a track to seal a garage's vehicle entrance.",
    why: "The entrance needs to be wide enough for a vehicle to pass through, which no ordinary hinged door can span without leaving the garage exposed to weather and intruders when closed.",
    has: ["garage door track", "spring"],
  },
  {
    slug: "garage-door-track",
    name: "Garage Door Track",
    what: "A curved steel rail along the ceiling and wall that guides a garage door's rollers as it opens.",
    why: "A garage door needs to travel from vertical to horizontal without a person guiding it — the fixed curved rail is what constrains that path every time.",
    has: ["steel"],
  },
  {
    slug: "workbench",
    name: "Workbench",
    what: "A sturdy flat-topped table built for holding tools and materials during repair or building work.",
    why: "Tinkering and repair need a stable surface at working height that can take scratches, spills, and clamped-down force without damaging household furniture.",
    has: ["tabletop", "legs"],
  },
  {
    slug: "garage-shelving",
    name: "Garage Shelving",
    what: "Open-frame shelving fixed to a garage wall for storing bins, tools, and yard equipment.",
    why: "Floor space in a garage is needed for the car and for moving around it — elevating storage onto wall-mounted shelves keeps clutter up off that floor.",
    has: ["wood", "steel"],
  },
  {
    slug: "toolbox",
    name: "Toolbox",
    what: "A portable case with compartments for storing and carrying hand tools.",
    why: "Loose tools scattered across a workbench get lost or damaged, and most repair jobs happen away from the garage — a single case keeps a working set organized and lets the whole kit travel to wherever the job is.",
    has: ["tool tray", "latch", "toolbox handle"],
  },
  {
    slug: "tool-tray",
    name: "Tool Tray",
    what: "A shallow removable tray inside a toolbox that holds small parts and frequently used tools near the top.",
    why: "Small items like screws and bits sink to the bottom of a deep case and take forever to find — a tray near the top keeps the most-used pieces visible and reachable first.",
    has: ["polymer"],
  },
  {
    slug: "latch",
    name: "Latch",
    what: "A spring-loaded metal clasp that locks a toolbox's lid shut.",
    why: "Tools are heavy and the box gets carried, tipped, and thrown in a truck bed — a latch keeps the lid from popping open and spilling everything the moment it's tilted.",
    has: ["steel"],
  },
  {
    slug: "toolbox-handle",
    name: "Toolbox Handle",
    what: "A folding metal grip on top of a toolbox for carrying it.",
    why: "The box needs to be lifted and carried one-handed by weight balanced underneath it — a handle centered on top is what makes that possible instead of gripping the case's edges.",
    has: ["steel"],
  },
  {
    slug: "car",
    name: "Car",
    what: "A wheeled motor vehicle for transporting people over roads.",
    why: "Walking or a bicycle can't cover long distances quickly or carry much cargo — an enclosed motorized vehicle covers far more ground per hour while shielding passengers from weather and carrying groceries, luggage, or several people at once.",
    has: ["engine", "car wheels", "car seats", "car battery"],
  },
  {
    slug: "engine",
    name: "Engine",
    what: "A combustion mechanism that converts fuel into the mechanical force that turns a car's wheels.",
    why: "Wheels alone don't move a car forward — something has to supply continuous rotating force, and the engine is what converts stored energy in fuel into exactly that.",
    has: ["pistons", "spark plug"],
  },
  {
    slug: "pistons",
    name: "Pistons",
    what: "Cylindrical plungers inside an engine that get pushed by burning fuel and drive a rotating crankshaft.",
    why: "Burning fuel expands rapidly in a sealed space — a piston is what catches that expansion and converts it into a straight push, which the crankshaft then turns into rotation.",
    has: ["steel"],
  },
  {
    slug: "spark-plug",
    name: "Spark Plug",
    what: "A small device that fires an electric spark inside an engine's cylinder to ignite the fuel-air mixture.",
    why: "Compressed fuel and air don't combust reliably on their own at the exact right moment — a timed spark is what triggers ignition precisely when the piston is positioned to use the resulting push.",
    has: ["steel", "ceramic"],
  },
  {
    slug: "car-wheels",
    name: "Car Wheels",
    what: "Rubber-tired metal rims that a car's engine turns to drive it forward and that support its whole weight.",
    why: "The car's whole weight and forward motion both rest entirely on four contact patches with the road — wheels are what bear that load while also being the point the engine's rotating force is actually applied to the ground.",
    has: ["tire", "rim"],
  },
  {
    slug: "tire",
    name: "Tire",
    what: "A ring of reinforced rubber mounted around a wheel's rim, filled with pressurized air.",
    why: "Bare metal rims would grip poorly and transmit every bump straight into the frame — a flexible air-filled tire cushions impacts, and its rubber tread is what actually grips the road.",
    has: ["rubber"],
  },
  {
    slug: "rim",
    name: "Rim",
    what: "The rigid metal wheel structure that a tire is mounted around and that bolts to the car's axle.",
    why: "The tire alone can't attach to the car or hold its shape under load — the rim gives it a fixed, round structure to seal against and a hub to bolt onto the axle.",
    has: ["steel"],
  },
  {
    slug: "car-seats",
    name: "Car Seats",
    what: "Cushioned seats inside a car fixed to its floor, built to hold occupants securely during motion.",
    why: "A moving vehicle needs occupants held firmly in place against acceleration, braking, and turns — a fixed, supportive seat does that in a way loose seating never could.",
    has: ["cushions", "car seat frame"],
  },
  {
    slug: "car-seat-frame",
    name: "Car Seat Frame",
    what: "The rigid metal skeleton inside a car seat that anchors it to the vehicle's floor and holds its shape under repeated impact.",
    why: "A crash or hard stop puts sudden extreme force through the seat — a metal frame is what keeps it from collapsing or tearing loose from the floor at exactly the moment it matters most.",
    has: ["steel"],
  },
  {
    slug: "car-battery",
    name: "Car Battery",
    what: "A rechargeable lead-acid battery mounted in a car's engine bay that supplies current to start the engine and run its electronics.",
    why: "An engine can't generate its own electricity until it's already spinning, but starting it in the first place takes a large burst of current for the starter motor — a charged battery supplies that burst from a dead stop, and keeps the lights, radio, and locks running whenever the engine is off.",
    has: ["lead plates", "sulfuric acid", "battery terminals"],
  },
  {
    slug: "lead-plates",
    name: "Lead Plates",
    what: "Grids of lead and lead oxide stacked inside a car battery's cells, submerged in acid.",
    why: "The chemical reaction that stores and releases charge needs a lot of exposed surface to react fast enough to crank a starter motor — thin plates stacked in parallel pack far more reactive surface into the case than a single solid block of lead could.",
    has: ["lead"],
  },
  {
    slug: "battery-terminals",
    name: "Battery Terminals",
    what: "The two lead-coated metal posts on top of a car battery, one positive and one negative, where cables clamp on to draw power.",
    why: "Current stored inside a sealed case is useless until it can reach the car's wiring — exposed posts give the starter and alternator cables a fixed point to clamp onto without opening the case.",
    has: ["lead"],
  },
  {
    slug: "lawnmower",
    name: "Lawnmower",
    what: "A wheeled machine with a spinning blade that cuts grass to an even height.",
    why: "Grass left unmowed grows uneven, attracts pests, and makes a yard hard to walk or play on — a fast-spinning blade cuts an entire lawn evenly in the time hand shears would take for a single patch.",
    has: ["mower blade", "engine", "mower wheels"],
  },
  {
    slug: "mower-blade",
    name: "Mower Blade",
    what: "A flat, sharpened steel bar mounted horizontally under a lawnmower that spins to cut grass as the machine moves forward.",
    why: "A stationary blade can't cut a moving swath of grass — spinning it fast enough turns a simple bar into something that slices every blade of grass it passes over instantly, without dragging across each one.",
    has: ["steel"],
  },
  {
    slug: "mower-wheels",
    name: "Mower Wheels",
    what: "Four simple rubber-tired wheels bolted to the corners of a lawnmower's deck that let it roll across the lawn.",
    why: "The mower has to roll smoothly over uneven grass while a person pushes or steers it — simple wheels do that without the load-bearing complexity a car's wheels need at highway speed.",
    has: ["rubber"],
  },
  {
    slug: "extension-cord",
    name: "Extension Cord",
    what: "A length of insulated cable with a plug on one end and a socket on the other, used to extend power from an outlet.",
    why: "An outlet is often too far from where a tool or light is actually needed in a garage — a cord bridges that distance so power reaches the work instead of the work needing to happen next to the wall.",
    has: ["wire", "polymer"],
  },
  {
    slug: "ladder",
    name: "Ladder",
    what: "A set of parallel rails with evenly spaced rungs, used to climb up to reach high places.",
    why: "Overhead shelves, gutters, and ceiling fixtures sit well above arm's reach standing on the floor — a ladder's rungs give a stable, repeatable set of steps up to that height instead of climbing on unstable furniture.",
    has: ["steel", "rungs"],
  },
  {
    slug: "fire-extinguisher",
    name: "Fire Extinguisher",
    what: "A portable pressurized canister that discharges a fire-suppressing agent to put out a small fire.",
    why: "A garage stores gasoline, oily rags, and a car battery within a few feet of power tools throwing sparks — a fire there can spread from spark to flame in seconds, faster than running for a hose or waiting on help, so a canister already on hand is what actually stops it before it grows.",
    has: ["extinguisher cylinder", "extinguishing agent", "pressure gauge"],
  },
  {
    slug: "extinguisher-cylinder",
    name: "Extinguisher Cylinder",
    what: "The sealed steel canister that holds a fire extinguisher's agent under pressure.",
    why: "The agent inside has to stay compressed and ready to discharge instantly after sitting unused for years — a rigid sealed metal shell is what holds that pressure without leaking or corroding through in storage.",
    has: ["steel"],
  },
  {
    slug: "extinguishing-agent",
    name: "Extinguishing Agent",
    what: "A dry chemical powder stored inside the cylinder that smothers a fire's oxygen supply when discharged.",
    why: "Water alone can spread a grease or electrical fire instead of stopping it — a fine powder blankets the flame and cuts off its oxygen and chemical reaction directly, working on fuel, electrical, and grease fires that water would make worse.",
    has: [],
  },
  {
    slug: "pressure-gauge",
    name: "Pressure Gauge",
    what: "A small dial on top of a fire extinguisher showing whether the cylinder is still pressurized and ready to use.",
    why: "A slow leak can empty a cylinder over months without any visible sign on the outside — the gauge's needle is the only way to confirm at a glance that it will actually discharge when needed, instead of finding out empty in an emergency.",
    has: [],
  },
];
