import type { Artifact } from "./types";

export const garage: Artifact[] = [
  {
    slug: "garage",
    name: "Garage",
    what: "A room or structure attached to or near a house where a car is parked and tools are stored.",
    why: "A car left outside is exposed to weather, theft, and temperature swings that degrade paint, batteries, and fluids. An enclosed space also gives a dedicated spot for tools and yard equipment that don't belong inside the living space.",
    has: ["garage door", "workbench", "garage shelving", "toolbox", "car"],
  },
  {
    slug: "garage-door",
    name: "Garage Door",
    what: "A large, sectioned door that rolls or tilts up along a track to seal a garage's vehicle entrance.",
    why: "The entrance needs to be wide enough for a vehicle to pass through, which no ordinary hinged door can span without leaving the garage exposed to weather and intruders when closed.",
    has: ["garage door track", "spring"],
  },
  {
    slug: "garage-door-track",
    name: "Garage Door Track",
    what: "A curved steel rail along the ceiling and wall that guides a garage door's rollers as it opens.",
    why: "A garage door needs to travel from vertical to horizontal without a person guiding it — the fixed curved rail is what constrains that path every time.",
    has: ["steel"],
  },
  {
    slug: "workbench",
    name: "Workbench",
    what: "A sturdy flat-topped table built for holding tools and materials during repair or building work.",
    why: "Tinkering and repair need a stable surface at working height that can take scratches, spills, and clamped-down force without damaging household furniture.",
    has: ["tabletop", "legs"],
  },
  {
    slug: "garage-shelving",
    name: "Garage Shelving",
    what: "Open-frame shelving fixed to a garage wall for storing bins, tools, and yard equipment.",
    why: "Floor space in a garage is needed for the car and for moving around it — elevating storage onto wall-mounted shelves keeps clutter up off that floor.",
    has: ["wood", "steel"],
  },
  {
    slug: "toolbox",
    name: "Toolbox",
    what: "A portable case with compartments for storing and carrying hand tools.",
    why: "Loose tools scattered across a workbench get lost or damaged, and most repair jobs happen away from the garage — a single case keeps a working set organized and lets the whole kit travel to wherever the job is.",
    has: ["tool tray", "latch", "toolbox handle"],
  },
  {
    slug: "tool-tray",
    name: "Tool Tray",
    what: "A shallow removable tray inside a toolbox that holds small parts and frequently used tools near the top.",
    why: "Small items like screws and bits sink to the bottom of a deep case and take forever to find — a tray near the top keeps the most-used pieces visible and reachable first.",
    has: ["polymer"],
  },
  {
    slug: "latch",
    name: "Latch",
    what: "A spring-loaded metal clasp that locks a toolbox's lid shut.",
    why: "Tools are heavy and the box gets carried, tipped, and thrown in a truck bed — a latch keeps the lid from popping open and spilling everything the moment it's tilted.",
    has: ["steel"],
  },
  {
    slug: "toolbox-handle",
    name: "Toolbox Handle",
    what: "A folding metal grip on top of a toolbox for carrying it.",
    why: "The box needs to be lifted and carried one-handed by weight balanced underneath it — a handle centered on top is what makes that possible instead of gripping the case's edges.",
    has: ["steel"],
  },
  {
    slug: "car",
    name: "Car",
    what: "A wheeled motor vehicle for transporting people over roads.",
    why: "Walking or a bicycle can't cover long distances quickly or carry much cargo — an enclosed motorized vehicle covers far more ground per hour while shielding passengers from weather and carrying groceries, luggage, or several people at once.",
    has: ["engine", "car wheels", "car seats"],
  },
  {
    slug: "engine",
    name: "Engine",
    what: "A combustion mechanism that converts fuel into the mechanical force that turns a car's wheels.",
    why: "Wheels alone don't move a car forward — something has to supply continuous rotating force, and the engine is what converts stored energy in fuel into exactly that.",
    has: ["pistons", "spark plug"],
  },
  {
    slug: "pistons",
    name: "Pistons",
    what: "Cylindrical plungers inside an engine that get pushed by burning fuel and drive a rotating crankshaft.",
    why: "Burning fuel expands rapidly in a sealed space — a piston is what catches that expansion and converts it into a straight push, which the crankshaft then turns into rotation.",
    has: ["steel"],
  },
  {
    slug: "spark-plug",
    name: "Spark Plug",
    what: "A small device that fires an electric spark inside an engine's cylinder to ignite the fuel-air mixture.",
    why: "Compressed fuel and air don't combust reliably on their own at the exact right moment — a timed spark is what triggers ignition precisely when the piston is positioned to use the resulting push.",
    has: ["steel", "ceramic"],
  },
  {
    slug: "car-wheels",
    name: "Car Wheels",
    what: "Rubber-tired metal rims that a car's engine turns to drive it forward and that support its whole weight.",
    why: "The car's whole weight and forward motion both rest entirely on four contact patches with the road — wheels are what bear that load while also being the point the engine's rotating force is actually applied to the ground.",
    has: ["tire", "rim"],
  },
  {
    slug: "tire",
    name: "Tire",
    what: "A ring of reinforced rubber mounted around a wheel's rim, filled with pressurized air.",
    why: "Bare metal rims would grip poorly and transmit every bump straight into the frame — a flexible air-filled tire cushions impacts, and its rubber tread is what actually grips the road.",
    has: ["rubber"],
  },
  {
    slug: "rim",
    name: "Rim",
    what: "The rigid metal wheel structure that a tire is mounted around and that bolts to the car's axle.",
    why: "The tire alone can't attach to the car or hold its shape under load — the rim gives it a fixed, round structure to seal against and a hub to bolt onto the axle.",
    has: ["steel"],
  },
  {
    slug: "car-seats",
    name: "Car Seats",
    what: "Cushioned seats inside a car fixed to its floor, built to hold occupants securely during motion.",
    why: "A moving vehicle needs occupants held firmly in place against acceleration, braking, and turns — a fixed, supportive seat does that in a way loose seating never could.",
    has: ["cushions", "car seat frame"],
  },
  {
    slug: "car-seat-frame",
    name: "Car Seat Frame",
    what: "The rigid metal skeleton inside a car seat that anchors it to the vehicle's floor and holds its shape under repeated impact.",
    why: "A crash or hard stop puts sudden extreme force through the seat — a metal frame is what keeps it from collapsing or tearing loose from the floor at exactly the moment it matters most.",
    has: ["steel"],
  },
];
