import type { Artifact } from "./types";

export const homeTheater: Artifact[] = [
  {
    slug: "home-theater",
    name: "Home Theater",
    what: "A room set up with a large screen, surround sound, and dedicated seating for watching movies.",
    why: "A regular living room's TV and seating are angled for everyday use, not focused viewing — a dedicated theater room controls light, sound, and sightlines the way a commercial theater does, just at home.",
    has: ["projector", "theater seating", "surround speakers", "projection screen", "AV receiver", "popcorn machine", "media console"],
  },
  {
    slug: "projector",
    name: "Projector",
    what: "A device that casts a large image onto a screen or wall using a bright internal light source.",
    why: "A flat-panel screen only gets so big before cost and size become impractical — projecting light onto a separate surface produces a far larger image for a fraction of the cost of an equivalent flat panel.",
    has: ["projector lens", "projector bulb"],
  },
  {
    slug: "projector-lens",
    name: "Projector Lens",
    what: "A precisely shaped glass lens that focuses and enlarges a projector's internal image onto a distant screen.",
    why: "Light leaving the source alone would just spread into a blurry glow — the lens bends and focuses it into a sharp, enlarged, correctly proportioned image at whatever distance the screen sits.",
    has: ["glass"],
  },
  {
    slug: "projector-bulb",
    name: "Projector Bulb",
    what: "An extremely bright lamp inside a projector that provides the light source for the projected image.",
    why: "Enlarging an image dozens of times over spreads its light thin — the bulb has to be far brighter than a normal light source just to keep the final projected image visible in a lit room.",
    has: [],
  },
  {
    slug: "theater-seating",
    name: "Theater Seating",
    what: "Reclined, cushioned individual seats arranged in rows facing a screen.",
    why: "Watching a long movie needs sustained comfort a sofa's upright cushions don't give for hours at a stretch — reclined individual seats support the body the way a commercial theater's seats do.",
    has: ["cushions", "legs"],
  },
  {
    slug: "surround-speakers",
    name: "Surround Speakers",
    what: "Multiple speakers placed around a room's perimeter that reproduce sound from different directions at once.",
    why: "A single set of front speakers can't recreate sound coming from behind or beside a viewer — placing speakers around the room reproduces the directional sense a movie's mix is built to use.",
    has: ["speaker", "wire"],
  },
  {
    slug: "projection-screen",
    name: "Projection Screen",
    what: "A large flat white or gray surface, either fixed or retractable, that a projector's image is displayed on.",
    why: "Projecting onto a bare wall scatters light unevenly and picks up the wall's own color and texture — a screen's optimized surface reflects light evenly for a sharper, more accurate image.",
    has: ["fabric", "screen frame"],
  },
  {
    slug: "screen-frame",
    name: "Screen Frame",
    what: "The rigid border that holds a projection screen's fabric taut and flat.",
    why: "Loose fabric would sag, wrinkle, and distort the image — a tensioned frame around the edges keeps the surface perfectly flat for a clean picture.",
    has: [],
  },
  {
    slug: "av-receiver",
    name: "AV Receiver",
    what: "A central unit that receives audio and video signals from a source and routes them to speakers and a screen.",
    why: "A projector and surround speakers all need to be fed the same synced signal from one source — a receiver decodes and splits that signal to every speaker and the screen at once instead of wiring each device to the source separately.",
    has: ["receiver circuit board", "volume dial"],
  },
  {
    slug: "receiver-circuit-board",
    name: "Receiver Circuit Board",
    what: "The internal electronic board inside a receiver that decodes incoming audio and video signals and routes them to the right output.",
    why: "Raw audio and video signals need to be split into channels — left, right, center, subwoofer, screen — and amplified for each one; the board is what actually does that decoding and routing instead of one wire trying to carry everything.",
    has: [],
  },
  {
    slug: "volume-dial",
    name: "Volume Dial",
    what: "A rotating knob on a receiver that adjusts the overall output level to the speakers.",
    why: "Every source has a different natural loudness — one dial lets a listener set the whole system to a comfortable level regardless of what's playing, without adjusting each speaker separately.",
    has: ["shaft", "detents"],
  },
  {
    slug: "popcorn-machine",
    name: "Popcorn Machine",
    what: "A small countertop machine that pops kernels using direct heat in a metal kettle, made for home theater snacking.",
    why: "Stovetop popping needs constant attention and a pan, while a dedicated machine holds a kettle at steady heat and often keeps popped corn warm afterward — built specifically to give the fresh, oil-popped taste of a real theater's popper at home.",
    has: ["popcorn kettle", "motor"],
  },
  {
    slug: "popcorn-kettle",
    name: "Popcorn Kettle",
    what: "A small metal kettle inside a popcorn machine that holds kernels and oil directly over the heat source.",
    why: "Kernels need direct, even heat contact against the metal to pop reliably — sitting the kettle right against the heat source gives that fresh oil-popped result a hot-air machine can't replicate.",
    has: ["steel"],
  },
  {
    slug: "media-console",
    name: "Media Console",
    what: "A low cabinet that holds a projector, receiver, and other components beneath or beside the screen.",
    why: "Home theater equipment generates heat and needs ventilation while staying out of the sightline to the screen — a low cabinet keeps it low, organized, and hidden from view during a movie instead of stacked in the open.",
    has: ["wood"],
  },
];
