import type { Artifact } from "./types";

export const homeGym: Artifact[] = [
  {
    slug: "home-gym",
    name: "Home Gym",
    what: "A room set up with equipment for exercising at home.",
    why: "Consistent exercise needs equipment on hand at all times — a dedicated room removes the friction of traveling to a gym, which is often the difference between a habit and a missed workout.",
    has: ["treadmill", "dumbbells", "yoga mat", "exercise bike", "pull-up bar", "resistance bands", "jump rope", "weight bench"],
  },
  {
    slug: "treadmill",
    name: "Treadmill",
    what: "A machine with a moving belt that lets a person walk or run in place.",
    why: "Outdoor running depends on weather and daylight — a belt-driven surface lets the same motion happen indoors on a fixed, controlled schedule regardless of conditions outside.",
    has: ["running belt", "motor"],
  },
  {
    slug: "running-belt",
    name: "Running Belt",
    what: "A continuous loop of rubber-coated fabric that spins beneath a treadmill's deck.",
    why: "A runner's stride needs a surface that keeps moving backward under their feet at a matched pace, or they'd simply walk off the front of a fixed deck.",
    has: ["rubber"],
  },
  {
    slug: "dumbbells",
    name: "Dumbbells",
    what: "A pair of handheld weights, one gripped in each hand, used for resistance exercise.",
    why: "Muscle grows in response to resistance beyond what body weight alone provides — a fixed, gripped weight lets that resistance be applied precisely to isolated muscle groups.",
    has: ["steel", "dumbbell handle"],
  },
  {
    slug: "dumbbell-handle",
    name: "Dumbbell Handle",
    what: "The straight knurled bar between a dumbbell's two weighted ends.",
    why: "A smooth bar would slip out of a sweating hand mid-lift — the knurled texture bites into the grip instead, especially as the load gets heavier.",
    has: ["steel"],
  },
  {
    slug: "yoga-mat",
    name: "Yoga Mat",
    what: "A thin cushioned mat unrolled on the floor for exercises done lying or kneeling down.",
    why: "A bare hard floor is uncomfortable against joints and slips underfoot during floor exercises — a mat's grip and cushioning let a person hold poses without sliding or bruising knees and elbows.",
    has: ["rubber"],
  },
  {
    slug: "exercise-bike",
    name: "Exercise Bike",
    what: "A stationary bicycle with pedals and adjustable resistance for cardio exercise indoors.",
    why: "Cycling outdoors depends on weather, traffic, and daylight — a stationary bike gives the same pedaling motion and cardio effort in a fixed spot regardless of conditions outside, with resistance that can be dialed up without needing a hill.",
    has: ["pedals", "resistance mechanism"],
  },
  {
    slug: "pedals",
    name: "Pedals",
    what: "Foot platforms fixed to cranks that a rider pushes in a circular motion to turn the bike's flywheel.",
    why: "Turning a heavy flywheel by hand would be awkward and weak — pedals let the much stronger leg muscles drive that rotation instead, through a natural circular motion.",
    has: ["steel"],
  },
  {
    slug: "resistance-mechanism",
    name: "Resistance Mechanism",
    what: "An adjustable brake, usually magnetic, that varies how hard the flywheel is to pedal.",
    why: "A flywheel spinning freely gives almost no workout once it's moving — adding controllable resistance against that spin is what turns pedaling into actual muscular effort, adjustable to the rider's fitness level.",
    has: ["magnet"],
  },
  {
    slug: "pull-up-bar",
    name: "Pull-Up Bar",
    what: "A fixed horizontal bar mounted in a doorway or on a wall, gripped overhead for pull-up exercises.",
    why: "Building upper-body pulling strength needs something to hang full bodyweight from and pull against — a bar fixed well above head height at a doorway gives that without needing a full gym rack.",
    has: ["steel"],
  },
  {
    slug: "resistance-bands",
    name: "Resistance Bands",
    what: "Long elastic bands that stretch to provide resistance during exercise.",
    why: "Not every exercise needs a heavy fixed weight — an elastic band gives adjustable, portable resistance that scales with how far it's stretched, useful for stretching and rehab work free weights can't do as safely.",
    has: ["rubber"],
  },
  {
    slug: "jump-rope",
    name: "Jump Rope",
    what: "A rope with handles on each end, swung under the feet and jumped over repeatedly for cardio exercise.",
    why: "Cardio exercise doesn't always need a machine — swinging a rope under continuously jumping feet raises heart rate fast in a tiny footprint, useful when there's no room for a treadmill or bike.",
    has: ["rope", "handle"],
  },
  {
    slug: "weight-bench",
    name: "Weight Bench",
    what: "A padded bench, often with an adjustable backrest, used to support the body during weightlifting exercises.",
    why: "Dumbbells alone can't be used for presses or rows that need the torso flat or inclined — a stable bench holds the body in that position so those muscles can be loaded without the lifter having to balance standing.",
    has: ["bench frame", "bench padding"],
  },
  {
    slug: "bench-frame",
    name: "Bench Frame",
    what: "The tubular steel structure that holds a weight bench's legs and padded seat off the floor.",
    why: "A loaded bench takes repeated, uneven impact as a lifter sets weight down and pushes off it — a welded steel frame keeps that flexing from loosening or collapsing under a lifter's full bodyweight plus load.",
    has: ["steel"],
  },
  {
    slug: "bench-padding",
    name: "Bench Padding",
    what: "The cushioned layer wrapped over a weight bench's frame where the lifter lies or sits.",
    why: "Bare steel would dig into the spine and pelvis under load — a firm foam pad spreads that pressure out, while a durable outer fabric keeps the foam from tearing under repeated sliding contact.",
    has: ["foam", "fabric"],
  },
];
