import type { Artifact } from "./types";

export const kitchen: Artifact[] = [
  {
    slug: "kitchen",
    name: "Kitchen",
    what: "A room where humans prepare, cook, and store food.",
    why: "Raw food is often unsafe or hard to digest. Cooking breaks it down, kills pathogens, and makes more calories available. Storage keeps food from spoiling between meals.",
    has: ["knife", "stove", "refrigerator", "sink", "trash bin"],
  },
  {
    slug: "knife",
    name: "Knife",
    what: "A blade fixed to a handle, used to cut food into smaller pieces.",
    why: "Human teeth and hands can't efficiently reduce most raw ingredients to cookable or edible sizes. A knife concentrates force into a thin edge, cutting with far less effort.",
    has: ["blade", "handle", "edge"],
  },
  {
    slug: "stove",
    name: "Stove",
    what: "A controlled heat source for cooking, powered by gas flame or electric element.",
    why: "Cooking requires sustained, adjustable heat. Open fire is hard to control and unsafe indoors; a stove contains the heat and lets it be raised or lowered on demand.",
    has: ["burner", "control knob", "surface"],
  },
  {
    slug: "refrigerator",
    name: "Refrigerator",
    what: "An insulated, mechanically cooled cabinet that keeps food below room temperature.",
    why: "Bacteria multiply fast at room temperature and spoil food within hours or days. Cold slows that growth dramatically, letting food stay safe to eat for days or weeks.",
    has: ["compressor", "insulated cabinet", "refrigerator shelves"],
  },
  {
    slug: "blade",
    name: "Blade",
    what: "The thin, sharpened piece of metal that does the actual cutting.",
    why: "A hardened, narrow edge concentrates force into a small contact area, letting it slice through fibers that a blunt surface would just squash.",
    has: ["steel", "bevel"],
  },
  {
    slug: "handle",
    name: "Handle",
    what: "The grip attached to a blade or tool, shaped to be held by hand.",
    why: "A bare blade against skin would cut the user too. A handle gives a safe, controlled grip so force goes into the material being cut, not the hand.",
    has: ["polymer", "rivets"],
  },
  {
    slug: "edge",
    name: "Edge",
    what: "The extremely thin, sharpened line along a blade where cutting happens.",
    why: "The thinner the edge, the less force is needed to start a cut. Sharpening keeps that edge thin as everyday use gradually wears and rounds it down.",
    has: ["cutting angle", "burr"],
  },
  {
    slug: "burner",
    name: "Burner",
    what: "The individual heating point on a stove — a gas ring or electric coil.",
    why: "Separate burners let multiple pots be heated at different temperatures at the same time, instead of everything sharing one heat source.",
    has: ["gas jet", "igniter"],
  },
  {
    slug: "control-knob",
    name: "Control Knob",
    what: "A rotating dial that adjusts a burner's heat output.",
    why: "Different foods need different heat levels. A knob gives fine, immediate control instead of an all-or-nothing flame.",
    has: ["shaft", "detents"],
  },
  {
    slug: "surface",
    name: "Surface",
    what: "The flat, heat-resistant top a stove's burners sit in.",
    why: "It contains spills and holds pots steady while cooking, keeping heat and mess contained instead of spreading to the rest of the kitchen.",
    has: ["ceramic", "grate"],
  },
  {
    slug: "compressor",
    name: "Compressor",
    what: "A pump that compresses refrigerant gas to move heat out of a cabinet.",
    why: "Cold isn't created directly — heat has to be pumped out from somewhere. The compressor drives that cycle, and that pumping is what actually lowers the internal temperature.",
    has: ["motor", "refrigerant"],
  },
  {
    slug: "insulated-cabinet",
    name: "Insulated Cabinet",
    what: "The outer shell of a refrigerator, lined with insulating material.",
    why: "Without insulation, the cold air inside would constantly trade heat with the warmer room, forcing the compressor to run nonstop just to hold temperature.",
    has: ["insulation", "steel"],
  },
  {
    slug: "refrigerator-shelves",
    name: "Refrigerator Shelves",
    what: "The fixed or adjustable trays inside a refrigerator's cabinet that hold food.",
    why: "Stacking food loose would crush whatever's on the bottom and make anything at the back impossible to reach without unpacking everything above it.",
    has: ["glass", "wire"],
  },
  {
    slug: "bevel",
    name: "Bevel",
    what: "The angled, ground surface where the two faces of a blade meet to form its edge.",
    why: "A steep bevel makes a strong but blunt edge; a shallow one makes a sharp but fragile edge. The bevel angle is what tunes that trade-off.",
    has: [],
  },
  {
    slug: "cutting-angle",
    name: "Cutting Angle",
    what: "The angle at which a blade's two ground faces meet at its very tip.",
    why: "It's the single measurement that determines whether an edge is durable and blunt or sharp and fragile — everything else about sharpening is aimed at controlling this number.",
    has: [],
  },
  {
    slug: "burr",
    name: "Burr",
    what: "A thin, rolled-over ridge of metal left standing at the edge after grinding.",
    why: "Sharpening always raises a burr first. Knowing it's there and removing it is what separates a merely-ground edge from a genuinely sharp one.",
    has: [],
  },
  {
    slug: "gas-jet",
    name: "Gas Jet",
    what: "A small nozzle that releases pressurized gas in a controlled, even ring.",
    why: "An open, unrestricted gas line would flare unevenly. The jet's fixed opening shapes the gas into a stable ring of flame instead.",
    has: [],
  },
  {
    slug: "igniter",
    name: "Igniter",
    what: "A spark-generating component that lights gas as it's released.",
    why: "Gas alone doesn't combust on its own — something has to supply the first spark. Doing that automatically means never needing a match to start cooking.",
    has: [],
  },
  {
    slug: "shaft",
    name: "Shaft",
    what: "The rod connecting a knob a person turns to the valve or switch it controls.",
    why: "It transmits the twisting motion from outside the appliance to the mechanism actually doing the regulating, without exposing that mechanism to the user's hand.",
    has: [],
  },
  {
    slug: "detents",
    name: "Detents",
    what: "Small mechanical stops inside a knob that create resistance at set points as it turns.",
    why: "They let a person feel and repeat an exact setting, like medium heat, by touch alone, without having to look down and read a dial.",
    has: [],
  },
  {
    slug: "grate",
    name: "Grate",
    what: "A metal framework that sits over a burner to hold pots above the flame.",
    why: "A pot needs to sit above the flame with airflow underneath it, not directly on top of the burner smothering the fire.",
    has: [],
  },
  {
    slug: "motor",
    name: "Motor",
    what: "A component that converts electricity into rotating mechanical motion.",
    why: "Compressing gas takes continuous mechanical work. The motor is what supplies that work, drawing it straight from the wall outlet's electricity.",
    has: [],
  },
  {
    slug: "refrigerant",
    name: "Refrigerant",
    what: "A chemical that absorbs heat as it evaporates and releases it as it condenses.",
    why: "It's the substance actually carrying heat out of the cabinet. The compressor just cycles it between those two states over and over.",
    has: [],
  },
  {
    slug: "insulation",
    name: "Insulation",
    what: "A foam or fiber material packed between a cabinet's inner and outer walls.",
    why: "Trapped pockets of still air conduct heat far more slowly than the metal walls around them, so a layer of insulation is what actually keeps outside heat from reaching the cold interior.",
    has: [],
  },
  {
    slug: "trash-bin",
    name: "Trash Bin",
    what: "A lidded container for holding food waste and packaging until it's taken out.",
    why: "Food scraps and packaging rot and smell fast if left sitting in the open. Containing them immediately, with a lid, keeps odor and pests out of the room where food itself is prepared.",
    has: ["polymer", "lid"],
  },
  {
    slug: "lid",
    name: "Lid",
    what: "A hinged or removable cover fitted over a bin's opening.",
    why: "An open bin lets odor and flies escape straight into the room. A lid seals that opening except for the moment something's actually thrown away.",
    has: ["hinges"],
  },
];
