import type { Artifact } from "./types";

export const kitchen: Artifact[] = [
  {
    slug: "kitchen",
    name: "Kitchen",
    what: "A room where humans prepare, cook, and store food.",
    why: "Raw food is often unsafe or hard to digest. Cooking breaks it down, kills pathogens, and makes more calories available. Storage keeps food from spoiling between meals.",
    has: ["knife", "stove", "refrigerator", "kitchen sink", "trash bin", "cabinets", "dishwasher", "microwave", "coffee maker", "pantry", "toaster", "cutting board", "blender", "kettle", "spice rack", "dish towel", "oven mitt", "frying pan", "cooking pot", "garbage disposal"],
  },
  {
    slug: "knife",
    name: "Knife",
    what: "A blade fixed to a handle, used to cut food into smaller pieces.",
    why: "Human teeth and hands can't efficiently reduce most raw ingredients to cookable or edible sizes. A knife concentrates force into a thin edge, cutting with far less effort.",
    has: ["blade", "handle", "edge"],
  },
  {
    slug: "stove",
    name: "Stove",
    what: "A controlled heat source for cooking, powered by gas flame or electric element.",
    why: "Cooking requires sustained, adjustable heat. Open fire is hard to control and unsafe indoors; a stove contains the heat and lets it be raised or lowered on demand.",
    has: ["burner", "control knob", "surface", "oven"],
  },
  {
    slug: "refrigerator",
    name: "Refrigerator",
    what: "An insulated, mechanically cooled cabinet that keeps food below room temperature.",
    why: "Bacteria multiply fast at room temperature and spoil food within hours or days. Cold slows that growth dramatically, letting food stay safe to eat for days or weeks.",
    has: ["compressor", "insulated cabinet", "refrigerator shelves"],
  },
  {
    slug: "cabinets",
    name: "Cabinets",
    what: "A fixed set of built-in storage compartments along a kitchen wall, closed off by doors and holding dishes, cookware, and dry goods.",
    why: "Dishes and dry goods need to be kept off the counter and out of dust, but still within arm's reach while cooking — closed doors also keep splatter and steam from the stove off anything not currently in use.",
    has: ["cabinet shelves", "cabinet door"],
  },
  {
    slug: "cabinet-shelves",
    name: "Cabinet Shelves",
    what: "Fixed horizontal boards inside a cabinet that hold stacked dishes, pots, or dry goods.",
    why: "Stacking cookware directly on top of itself risks chipping and buries whatever's on the bottom. A shelf gives each item its own level instead of one deep pile.",
    has: ["wood"],
  },
  {
    slug: "cabinet-door",
    name: "Cabinet Door",
    what: "A small hinged panel that closes off a cabinet's opening.",
    why: "Grease and steam drift up from the stove during cooking. A closed door keeps that residue off dishes and food stored inside instead of settling directly on them.",
    has: ["wood", "hinges"],
  },
  {
    slug: "blade",
    name: "Blade",
    what: "The thin, sharpened piece of metal that does the actual cutting.",
    why: "A hardened, narrow edge concentrates force into a small contact area, letting it slice through fibers that a blunt surface would just squash.",
    has: ["steel", "bevel"],
  },
  {
    slug: "handle",
    name: "Handle",
    what: "The grip attached to a blade or tool, shaped to be held by hand.",
    why: "A bare blade against skin would cut the user too. A handle gives a safe, controlled grip so force goes into the material being cut, not the hand.",
    has: ["polymer", "rivets"],
  },
  {
    slug: "edge",
    name: "Edge",
    what: "The extremely thin, sharpened line along a blade where cutting happens.",
    why: "The thinner the edge, the less force is needed to start a cut. Sharpening keeps that edge thin as everyday use gradually wears and rounds it down.",
    has: ["cutting angle", "burr"],
  },
  {
    slug: "burner",
    name: "Burner",
    what: "The individual heating point on a stove — a gas ring or electric coil.",
    why: "Separate burners let multiple pots be heated at different temperatures at the same time, instead of everything sharing one heat source.",
    has: ["gas jet", "igniter"],
  },
  {
    slug: "control-knob",
    name: "Control Knob",
    what: "A rotating dial that adjusts a burner's heat output.",
    why: "Different foods need different heat levels. A knob gives fine, immediate control instead of an all-or-nothing flame.",
    has: ["shaft", "detents"],
  },
  {
    slug: "surface",
    name: "Surface",
    what: "The flat, heat-resistant top a stove's burners sit in.",
    why: "It contains spills and holds pots steady while cooking, keeping heat and mess contained instead of spreading to the rest of the kitchen.",
    has: ["ceramic", "grate"],
  },
  {
    slug: "compressor",
    name: "Compressor",
    what: "A pump that compresses refrigerant gas to move heat out of a cabinet.",
    why: "Cold isn't created directly — heat has to be pumped out from somewhere. The compressor drives that cycle, and that pumping is what actually lowers the internal temperature.",
    has: ["motor", "refrigerant"],
  },
  {
    slug: "insulated-cabinet",
    name: "Insulated Cabinet",
    what: "The outer shell of a refrigerator, lined with insulating material.",
    why: "Without insulation, the cold air inside would constantly trade heat with the warmer room, forcing the compressor to run nonstop just to hold temperature.",
    has: ["insulation", "steel"],
  },
  {
    slug: "refrigerator-shelves",
    name: "Refrigerator Shelves",
    what: "The fixed or adjustable trays inside a refrigerator's cabinet that hold food.",
    why: "Stacking food loose would crush whatever's on the bottom and make anything at the back impossible to reach without unpacking everything above it.",
    has: ["glass", "wire"],
  },
  {
    slug: "bevel",
    name: "Bevel",
    what: "The angled, ground surface where the two faces of a blade meet to form its edge.",
    why: "A steep bevel makes a strong but blunt edge; a shallow one makes a sharp but fragile edge. The bevel angle is what tunes that trade-off.",
    has: [],
  },
  {
    slug: "cutting-angle",
    name: "Cutting Angle",
    what: "The angle at which a blade's two ground faces meet at its very tip.",
    why: "It's the single measurement that determines whether an edge is durable and blunt or sharp and fragile — everything else about sharpening is aimed at controlling this number.",
    has: [],
  },
  {
    slug: "burr",
    name: "Burr",
    what: "A thin, rolled-over ridge of metal left standing at the edge after grinding.",
    why: "Sharpening always raises a burr first. Knowing it's there and removing it is what separates a merely-ground edge from a genuinely sharp one.",
    has: [],
  },
  {
    slug: "gas-jet",
    name: "Gas Jet",
    what: "A small nozzle that releases pressurized gas in a controlled, even ring.",
    why: "An open, unrestricted gas line would flare unevenly. The jet's fixed opening shapes the gas into a stable ring of flame instead.",
    has: [],
  },
  {
    slug: "igniter",
    name: "Igniter",
    what: "A spark-generating component that lights gas as it's released.",
    why: "Gas alone doesn't combust on its own — something has to supply the first spark. Doing that automatically means never needing a match to start cooking.",
    has: [],
  },
  {
    slug: "shaft",
    name: "Shaft",
    what: "The rod connecting a knob a person turns to the valve or switch it controls.",
    why: "It transmits the twisting motion from outside the appliance to the mechanism actually doing the regulating, without exposing that mechanism to the user's hand.",
    has: [],
  },
  {
    slug: "detents",
    name: "Detents",
    what: "Small mechanical stops inside a knob that create resistance at set points as it turns.",
    why: "They let a person feel and repeat an exact setting, like medium heat, by touch alone, without having to look down and read a dial.",
    has: [],
  },
  {
    slug: "grate",
    name: "Grate",
    what: "A metal framework that sits over a burner to hold pots above the flame.",
    why: "A pot needs to sit above the flame with airflow underneath it, not directly on top of the burner smothering the fire.",
    has: [],
  },
  {
    slug: "motor",
    name: "Motor",
    what: "A component that converts electricity into rotating mechanical motion.",
    why: "Compressing gas takes continuous mechanical work. The motor is what supplies that work, drawing it straight from the wall outlet's electricity.",
    has: [],
  },
  {
    slug: "refrigerant",
    name: "Refrigerant",
    what: "A chemical that absorbs heat as it evaporates and releases it as it condenses.",
    why: "It's the substance actually carrying heat out of the cabinet. The compressor just cycles it between those two states over and over.",
    has: [],
  },
  {
    slug: "insulation",
    name: "Insulation",
    what: "A foam or fiber material packed between a cabinet's inner and outer walls.",
    why: "Trapped pockets of still air conduct heat far more slowly than the metal walls around them, so a layer of insulation is what actually keeps outside heat from reaching the cold interior.",
    has: [],
  },
  {
    slug: "oven",
    name: "Oven",
    what: "An enclosed insulated chamber in a stove that surrounds food with heat for baking and roasting.",
    why: "Some foods need slow, even heat from every side, not the direct exposed flame a burner gives. A sealed insulated chamber holds a steady heat and traps the moisture an open flame would let escape.",
    has: ["heating element", "insulation"],
  },
  {
    slug: "heating-element",
    name: "Heating Element",
    what: "A resistive coil or gas burner tube inside an oven that generates the heat filling the chamber.",
    why: "Something has to actually produce heat inside the sealed chamber. The element is what converts electricity or gas into the steady heat the whole oven depends on.",
    has: [],
  },
  {
    slug: "kitchen-sink",
    name: "Kitchen Sink",
    what: "A large plumbed basin set into a kitchen counter, with running hot and cold water, used for washing dishes, produce, and hands.",
    why: "Cookware and stacked dishes need a basin deep and wide enough to submerge a full pot, and food scraps rinsed off during prep go straight down the drain — a basin sized for washing hands and a face, like a bathroom sink, can't hold a stockpot or take that kind of load.",
    has: ["kitchen sink basin", "faucet", "drain"],
  },
  {
    slug: "kitchen-sink-basin",
    name: "Kitchen Sink Basin",
    what: "The wide, deep bowl of a kitchen sink that holds water, dishes, and cookware during washing.",
    why: "Ceramic chips and stains under the repeated impact of dropped pots and cast iron, while stainless steel shrugs off that abuse and stays non-porous through years of scrubbing with abrasive pads and hot grease.",
    has: ["steel"],
  },
  {
    slug: "trash-bin",
    name: "Trash Bin",
    what: "A lidded container for holding food waste and packaging until it's taken out.",
    why: "Food scraps and packaging rot and smell fast if left sitting in the open. Containing them immediately, with a lid, keeps odor and pests out of the room where food itself is prepared.",
    has: ["polymer", "lid"],
  },
  {
    slug: "lid",
    name: "Lid",
    what: "A hinged or removable cover fitted over a bin's opening.",
    why: "An open bin lets odor and flies escape straight into the room. A lid seals that opening except for the moment something's actually thrown away.",
    has: ["hinges"],
  },
  {
    slug: "dishwasher",
    name: "Dishwasher",
    what: "A plumbed kitchen appliance that sprays hot water and detergent over stacked dishes to clean them.",
    why: "Washing a full load by hand at the sink takes minutes per plate and can't sustain the near-scalding water a hand would never tolerate — running dishes through a sealed chamber lets the water run hotter and longer than washing by hand ever could.",
    has: ["spray arm", "dish rack", "dishwasher door"],
  },
  {
    slug: "spray-arm",
    name: "Spray Arm",
    what: "A perforated rotating arm inside a dishwasher that sprays water across the dishes above and below it.",
    why: "Water needs to reach every dish from multiple angles without a person redirecting it mid-cycle — the arm's own water pressure spins it as it sprays, sweeping jets across the whole rack automatically.",
    has: ["polymer"],
  },
  {
    slug: "dish-rack",
    name: "Dish Rack",
    what: "A wire framework inside a dishwasher that holds plates, bowls, and cups upright and separated.",
    why: "Dishes stacked flat against each other would block water from reaching every surface and could chip on contact — the rack's slots hold each piece angled and apart so spray reaches all sides.",
    has: ["wire"],
  },
  {
    slug: "dishwasher-door",
    name: "Dishwasher Door",
    what: "A hinged, sealed front panel that closes a dishwasher's wash chamber during a cycle.",
    why: "The chamber has to hold pressurized hot water and steam without leaking onto the kitchen floor, which needs a tighter seal than a household door built just to block light and dust.",
    has: ["steel", "gasket"],
  },
  {
    slug: "gasket",
    name: "Gasket",
    what: "A flexible rubber strip running around the edge of a dishwasher door that compresses against the frame when closed.",
    why: "Metal against metal always leaves microscopic gaps water finds its way through — the rubber compresses into those gaps and seals them, something a rigid material couldn't do.",
    has: ["rubber"],
  },
  {
    slug: "microwave",
    name: "Microwave",
    what: "A countertop appliance that uses electromagnetic waves to heat food quickly.",
    why: "Waves excite water molecules throughout food at once rather than just at the surface, so food heats through in minutes instead of the slow surface-inward heat transfer of a stove or oven.",
    has: ["magnetron", "turntable", "microwave door"],
  },
  {
    slug: "magnetron",
    name: "Magnetron",
    what: "A vacuum tube that generates microwaves by oscillating electrons in a magnetic field.",
    why: "Heating food through requires radiation powerful and precise enough to penetrate it evenly — the magnetron is the component that actually converts electricity into that specific wavelength.",
    has: [],
  },
  {
    slug: "turntable",
    name: "Turntable",
    what: "A rotating glass plate inside a microwave that spins food during cooking.",
    why: "Microwaves form uneven hot and cold spots inside the cavity — spinning the food constantly moves it through both zones, averaging out the heating instead of leaving cold, undercooked patches.",
    has: ["glass", "motor"],
  },
  {
    slug: "microwave-door",
    name: "Microwave Door",
    what: "A hinged door with a metal mesh window that seals a microwave's cavity shut during cooking.",
    why: "Microwaves have to stay fully contained inside the cavity, since leaking radiation is a safety hazard — the mesh window lets light out through holes too small for microwaves to pass, while the seal blocks any gap around the edge.",
    has: ["mesh screen", "hinges"],
  },
  {
    slug: "mesh-screen",
    name: "Mesh Screen",
    what: "A grid of small metal holes embedded in a microwave door's window.",
    why: "The holes are far smaller than a microwave's wavelength but larger than visible light's, so light passes through for visibility while the microwaves themselves are blocked and reflected back into the cavity.",
    has: ["steel"],
  },
  {
    slug: "coffee-maker",
    name: "Coffee Maker",
    what: "A countertop appliance that brews hot water through ground coffee to produce coffee.",
    why: "Steeping coffee grounds properly needs water held at a narrow near-boiling range for several minutes — a machine automates that heating and timing far more consistently than boiling a kettle and hand-pouring.",
    has: ["water reservoir", "heating coil", "carafe"],
  },
  {
    slug: "water-reservoir",
    name: "Water Reservoir",
    what: "A removable water tank on a coffee maker that holds water before it's heated and brewed.",
    why: "The machine needs a measured supply of water on hand between refills — a removable tank lets that supply be filled at the sink and carried back without moving the whole appliance.",
    has: ["polymer"],
  },
  {
    slug: "heating-coil",
    name: "Heating Coil",
    what: "A resistive wire coil that heats water as it flows past on its way to the grounds.",
    why: "Water needs to reach and hold near-boiling temperature for full extraction — resistance heating the coil directly warms the water passing over it far faster than heating the whole reservoir at once.",
    has: ["wire"],
  },
  {
    slug: "carafe",
    name: "Carafe",
    what: "A glass or thermal pot that catches brewed coffee as it drips from the filter basket.",
    why: "Brewed coffee needs somewhere to collect, ready to pour, without sitting directly under the machine the whole time — a separate, removable pot lets it be poured immediately or carried to the table.",
    has: ["glass"],
  },
  {
    slug: "pantry",
    name: "Pantry",
    what: "A small enclosed storage space or closet in the kitchen for shelf-stable food.",
    why: "Canned goods, grains, and boxed food don't need refrigeration but do need to be kept dry, dark, and off the floor — a dedicated closet holds a much deeper stock than cabinet shelves alone can fit.",
    has: ["pantry shelves", "food containers"],
  },
  {
    slug: "pantry-shelves",
    name: "Pantry Shelves",
    what: "Deep fixed wooden shelves lining a pantry, spaced for stacking cans, boxes, and jars.",
    why: "Dry goods need to be visible and reachable without unstacking everything else — evenly spaced shelves let each type of food get its own row instead of one deep pile.",
    has: ["wood"],
  },
  {
    slug: "food-containers",
    name: "Food Containers",
    what: "Airtight containers that bulk dry goods like flour, rice, or cereal are transferred into for storage.",
    why: "Bags split, spill, and let pests in once opened — a sealed rigid container keeps opened dry goods fresh and pest-free far longer than the original packaging.",
    has: ["polymer"],
  },
  {
    slug: "toaster",
    name: "Toaster",
    what: "A countertop appliance with slots that toasts bread using radiant heating elements.",
    why: "Toasting browns and crisps bread's surface by driving off moisture with direct radiant heat — something a stove's open flame or oven's slower ambient heat can't do as fast or evenly to a single slice.",
    has: ["toaster slots", "radiant coils", "lever"],
  },
  {
    slug: "toaster-slots",
    name: "Toaster Slots",
    what: "Narrow vertical openings in a toaster's top sized to hold a slice of bread upright between the heating coils.",
    why: "Bread needs to stand upright with both faces evenly exposed to the coils on either side — a horizontal tray would only heat one face at a time.",
    has: ["steel"],
  },
  {
    slug: "radiant-coils",
    name: "Radiant Coils",
    what: "Thin exposed nichrome wire coils inside a toaster that glow red-hot and radiate heat directly onto bread.",
    why: "Bread needs direct, close-range heat hitting its surface within seconds, not a slow warm chamber — bare glowing coils radiate that heat straight across the slot instead of relying on trapped air.",
    has: ["wire"],
  },
  {
    slug: "lever",
    name: "Lever",
    what: "A spring-loaded lever on a toaster's side that lowers bread into the slot and locks it down until toasting finishes.",
    why: "Bread has to be held down inside the hot slot for the whole cycle, then released and popped back up automatically once done, without a hand staying on it the entire time.",
    has: ["spring"],
  },
  {
    slug: "cutting-board",
    name: "Cutting Board",
    what: "A flat rigid board used as a protective surface under a knife while cutting food.",
    why: "Cutting directly on a countertop dulls the blade fast and can gouge or stain the surface — a dedicated board takes that repeated edge contact instead, and can be pulled out only when needed.",
    has: ["wood"],
  },
  {
    slug: "blender",
    name: "Blender",
    what: "A countertop appliance with spinning blades at the bottom of a jar, used to puree or mix liquids and soft food.",
    why: "Chopping by hand can't fully break food down into a smooth, uniform liquid — spinning blades at high speed shear food far finer and faster than any knife, turning chunks into a pourable puree.",
    has: ["blender jar", "blender blades", "motor"],
  },
  {
    slug: "kettle",
    name: "Kettle",
    what: "A kitchen appliance that heats water to boiling for tea, coffee, or general use.",
    why: "Boiling water in a pot on the stove takes longer to reach a full boil and needs to be watched by hand — a kettle heats faster through direct contact and shuts off automatically once boiling, freeing attention elsewhere.",
    has: ["kettle body", "heating coil", "auto-shutoff switch"],
  },
  {
    slug: "kettle-body",
    name: "Kettle Body",
    what: "The outer vessel of a kettle that holds water above its heating coil.",
    why: "Water has to be contained in a sealed, pourable shape while it heats to near-boiling, without leaking or exposing a hand to a surface that hot.",
    has: ["steel", "spout"],
  },
  {
    slug: "spout",
    name: "Spout",
    what: "The narrow angled opening at the top of a kettle body that water pours from.",
    why: "A wide open top would splash boiling water everywhere when tipped — narrowing the opening directs the stream into a controlled pour instead.",
    has: [],
  },
  {
    slug: "auto-shutoff-switch",
    name: "Auto-Shutoff Switch",
    what: "A steam-sensing switch inside a kettle that cuts power once the water reaches a full boil.",
    why: "Boiling water left unattended risks running the kettle dry and damaging it — sensing steam at boiling point and cutting power automatically removes the need to watch it.",
    has: ["contacts", "spring"],
  },
  {
    slug: "spice-rack",
    name: "Spice Rack",
    what: "A small shelved rack, mounted or freestanding, that holds spice jars within reach of the stove.",
    why: "Spices get used in small pinches throughout cooking and need to be visible and grabbable without opening a deep cabinet each time — a shallow rack keeps every jar's label facing out at a glance.",
    has: ["wood", "spice jars"],
  },
  {
    slug: "spice-jars",
    name: "Spice Jars",
    what: "Small uniform glass jars, each holding one ground spice or herb.",
    why: "Spices lose potency fast when exposed to air and light — a small sealed jar limits how much is exposed at once and keeps the rest fresh until it's needed.",
    has: ["glass", "jar lid"],
  },
  {
    slug: "jar-lid",
    name: "Jar Lid",
    what: "A small screw-on cap that seals a spice jar's opening, often with a built-in shaker.",
    why: "A spice jar gets opened and closed dozens of times before it's empty — a screw cap reseals it tightly each time, and a built-in shaker controls how much comes out in one shake.",
    has: ["polymer"],
  },
  {
    slug: "blender-jar",
    name: "Blender Jar",
    what: "A tall, tapered container that holds food and liquid above a blender's spinning blades.",
    why: "The tapered shape keeps pulling food back down toward the blades as it spins, instead of letting chunks sit stuck against the walls out of the blade's reach.",
    has: ["glass"],
  },
  {
    slug: "blender-blades",
    name: "Blender Blades",
    what: "A cluster of angled metal blades fixed to a spinning shaft at the bottom of a blender jar.",
    why: "A single flat blade would just push food around — angled blades set at different heights catch and cut food from multiple directions as they spin, pulling everything into the vortex.",
    has: ["steel"],
  },
  {
    slug: "dish-towel",
    name: "Dish Towel",
    what: "An absorbent cloth kept in the kitchen for drying hands, dishes, and wiping counters.",
    why: "Water and food residue on hands or a counter needs to be wiped up immediately during cooking, and a paper towel runs out fast — a reusable cloth towel stays within reach and gets washed and reused instead of thrown away each time.",
    has: ["fabric"],
  },
  {
    slug: "oven-mitt",
    name: "Oven Mitt",
    what: "A thick insulated glove worn to handle hot pots, pans, and oven racks without burning the hand.",
    why: "Metal cookware and oven racks reach temperatures well above what skin can touch safely — a thick insulating layer between hand and hot surface is what lets someone grip and lift it without getting burned.",
    has: ["fabric"],
  },
  {
    slug: "frying-pan",
    name: "Frying Pan",
    what: "A shallow, handled metal pan used to cook food directly over a stove's heat.",
    why: "Food seared or fried needs to sit in direct, even contact with a hot surface with room to be flipped or stirred — a flat-bottomed pan with raised sides holds food against that heat without trapping in steam the way a pot's lid does.",
    has: ["pan surface", "pan handle"],
  },
  {
    slug: "pan-surface",
    name: "Pan Surface",
    what: "The flat, heat-conducting base of a frying pan that food sits directly on.",
    why: "It has to spread a burner's heat evenly across the whole cooking area and release food cleanly afterward — a bare metal surface alone lets food stick and burn at the first hot spot instead.",
    has: ["aluminum", "non-stick coating"],
  },
  {
    slug: "non-stick-coating",
    name: "Non-Stick Coating",
    what: "A thin polymer layer bonded to a pan's cooking surface that food won't stick to.",
    why: "Its molecular structure gives food proteins almost nothing to bond to, so a fried egg or fish fillet lifts free with a spatula instead of tearing apart on a bare metal surface it would otherwise fuse to.",
    has: ["polymer"],
  },
  {
    slug: "pan-handle",
    name: "Pan Handle",
    what: "A long metal grip riveted to a frying pan's side, kept clear of the direct heat below.",
    why: "The pan surface reaches temperatures that would burn skin instantly — extending the grip away from that surface and riveting it on keeps a hand safely out of range while still controlling the pan.",
    has: ["steel", "rivets"],
  },
  {
    slug: "cooking-pot",
    name: "Cooking Pot",
    what: "A tall, straight-sided metal vessel with two side handles and a lid, used to boil or simmer food in liquid on a stove.",
    why: "Boiling and simmering need a deep vessel that holds a large volume of liquid without splashing out, plus a lid to trap the rising steam — a frying pan's shallow, open shape can't hold enough liquid or contain the steam a rolling boil throws off.",
    has: ["pot body", "pot handles", "pot lid"],
  },
  {
    slug: "pot-body",
    name: "Pot Body",
    what: "The deep, straight-walled vessel that holds liquid and food above a stove's heat.",
    why: "Liquid held at a boil for long stretches slowly pits and corrodes softer metals — stainless steel shrugs that off, where the frying pan's aluminum trades that durability for faster heating and cooling.",
    has: ["steel"],
  },
  {
    slug: "pot-handles",
    name: "Pot Handles",
    what: "Two short, riveted loop handles fixed to opposite sides of a pot's body.",
    why: "A pot full of liquid is heavy and off-balance to lift one-handed — a handle on each side lets it be carried and poured level, unlike a frying pan's contents, light enough to toss and flip with a single long handle.",
    has: ["steel", "rivets"],
  },
  {
    slug: "pot-lid",
    name: "Pot Lid",
    what: "A flat or domed metal cover that sits over a pot's opening to trap rising heat and steam.",
    why: "Trapping steam keeps liquid at a rolling boil with less energy and shortens simmering time — left uncovered, that same heat escapes straight into the room instead of staying in the liquid.",
    has: ["steel"],
  },
  {
    slug: "garbage-disposal",
    name: "Garbage Disposal",
    what: "A motor-driven grinding unit mounted under a kitchen sink that shreds food scraps small enough to flush down the drain.",
    why: "Food scraps left in an open trash bin rot and draw pests fast, but most scraps are too big or fibrous to flush whole without clogging the pipe — grinding them fine first lets running water carry them straight into the sewer line instead.",
    has: ["impeller", "grind ring", "motor"],
  },
  {
    slug: "impeller",
    name: "Impeller",
    what: "A spinning steel plate with hinged lugs, mounted on a motor shaft inside a garbage disposal's grinding chamber.",
    why: "It doesn't cut on its own — spinning fast enough, its lugs fling food outward by centrifugal force against the fixed ring around it, where the actual shredding happens.",
    has: ["steel"],
  },
  {
    slug: "grind-ring",
    name: "Grind Ring",
    what: "A stationary, tooth-lined steel ring fixed around a garbage disposal's grinding chamber.",
    why: "Food flung outward by the impeller gets caught and torn between the ring's teeth, breaking it down until the pieces are small enough to pass through the ring's holes and out with the water.",
    has: ["steel"],
  },
];
