import type { Artifact } from "./types";

export const laundryRoom: Artifact[] = [
  {
    slug: "laundry-room",
    name: "Laundry Room",
    what: "A room equipped with machines for washing and drying clothes.",
    why: "Fabric holds onto sweat, oil, and stains that plain water alone won't lift. Dedicated machines agitate, heat, and spin clothes far more thoroughly than hand-washing, and doing it in one place keeps the mess and noise contained.",
    has: ["washing machine", "dryer", "laundry basket", "iron", "ironing board", "drying rack", "lint roller"],
  },
  {
    slug: "laundry-basket",
    name: "Laundry Basket",
    what: "A perforated basket for carrying and holding dirty clothes before they're washed.",
    why: "Dirty clothes pile up between wash days and need somewhere to sit — sealing sweat-damp fabric in a solid bin traps moisture and starts mildew, so the basket's open weave keeps air moving through the pile instead.",
    has: ["polymer", "basket handles"],
  },
  {
    slug: "basket-handles",
    name: "Basket Handles",
    what: "Two molded grips on opposite sides of a basket's rim, sized to be gripped one in each hand.",
    why: "A full basket of clothes is heavy and awkward to hug against the body — a grip on each side lets it be carried steadily with both hands and swung up onto a hip or into a machine.",
    has: ["polymer"],
  },
  {
    slug: "washing-machine",
    name: "Washing Machine",
    what: "A machine that agitates clothes in water and detergent, then spins them to remove the water.",
    why: "Hand-scrubbing clothes is slow and inconsistent. A motor-driven drum agitates every part of a load evenly, and spinning it fast afterward forces most of the water back out before drying.",
    has: ["drum", "motor"],
  },
  {
    slug: "drum",
    name: "Drum",
    what: "The perforated rotating cylinder inside a washing machine or dryer that holds clothes during a cycle.",
    why: "Clothes need to tumble freely without escaping or blocking drainage — the perforations let water or air in and out while the cylinder shape keeps the load moving evenly.",
    has: ["steel"],
  },
  {
    slug: "dryer",
    name: "Dryer",
    what: "A machine that tumbles damp clothes through heated air until the water in them evaporates.",
    why: "Air-drying is slow and space-consuming. Forcing hot air through a tumbling drum evaporates the remaining water in a fraction of the time.",
    has: ["drum", "heating element", "lint trap"],
  },
  {
    slug: "lint-trap",
    name: "Lint Trap",
    what: "A removable fine-mesh screen in a dryer's airflow path that catches lint shed from tumbling fabric.",
    why: "Every load sheds fibers into the airflow, and lint packed into the exhaust vent blocks airflow and ignites easily against the heating element — the trap catches it somewhere shallow and removable instead, so it can be cleared before each load rather than building up downstream.",
    has: ["wire", "polymer"],
  },
  {
    slug: "iron",
    name: "Iron",
    what: "A handheld appliance with a heated flat metal plate, pressed and glided over fabric to remove wrinkles.",
    why: "Fabric fibers set into wrinkled shapes as they dry — heat and pressure relax those fibers just long enough to press them flat again before they cool and hold the new shape.",
    has: ["soleplate", "iron handle", "steam vents"],
  },
  {
    slug: "soleplate",
    name: "Soleplate",
    what: "The flat, heated metal base of an iron that makes direct contact with fabric.",
    why: "It's the actual heat- and pressure-delivering surface — a smooth, evenly heated plate glides across fabric without snagging while transferring heat into it.",
    has: ["steel"],
  },
  {
    slug: "iron-handle",
    name: "Iron Handle",
    what: "An insulated grip on top of an iron, angled to keep the hand well above the heated plate.",
    why: "The plate beneath reaches temperatures that would burn skin instantly — the handle holds the hand a fixed safe distance above it while still letting the iron be pressed down with force.",
    has: ["polymer"],
  },
  {
    slug: "steam-vents",
    name: "Steam Vents",
    what: "Small holes across an iron's soleplate that release pressurized steam onto fabric.",
    why: "Dry heat alone can scorch fabric before it fully relaxes the fibers — steam carries heat into the weave faster and at a lower plate temperature, cutting the risk of burning it.",
    has: [],
  },
  {
    slug: "ironing-board",
    name: "Ironing Board",
    what: "A narrow, height-adjustable padded board that fabric is laid flat on while being ironed.",
    why: "Ironing directly on a table would scorch or mark the furniture and doesn't let heat or steam pass through — a padded board holds fabric taut at a comfortable working height and vents steam through instead of trapping it.",
    has: ["board top", "folding legs"],
  },
  {
    slug: "board-top",
    name: "Board Top",
    what: "The narrow, padded, heat-resistant surface an ironing board's fabric is laid across.",
    why: "Fabric needs a firm but slightly cushioned surface to press against, padded enough to iron out wrinkles without denting or scorching from direct contact with a bare metal plate.",
    has: ["fabric"],
  },
  {
    slug: "folding-legs",
    name: "Folding Legs",
    what: "X-shaped metal legs under an ironing board that fold flat against the board for storage.",
    why: "The board is only set up while ironing and needs to store flat against a wall the rest of the time — legs that fold in let the whole thing collapse to a thin profile instead of taking up floor space permanently.",
    has: ["steel"],
  },
  {
    slug: "drying-rack",
    name: "Drying Rack",
    what: "A folding rack of parallel bars that clothes are draped over to air-dry.",
    why: "Some fabrics shrink, warp, or lose shape in a tumble dryer's heat — laying them flat or draped over a rack lets them dry gently at room temperature instead.",
    has: ["wire"],
  },
  {
    slug: "lint-roller",
    name: "Lint Roller",
    what: "A handheld roller covered in adhesive sheets, rolled over fabric to pick up lint and pet hair.",
    why: "Lint and shed hair cling to clothing through static and can't just be brushed off — a sticky roller picks them up directly on contact, something a hand or brush can't do without leaving residue behind.",
    has: ["polymer"],
  },
];
