import type { Artifact } from "./types";

export const livingRoom: Artifact[] = [
  {
    slug: "living-room",
    name: "Living Room",
    what: "A room where humans gather, relax, and share information.",
    why: "Sitting on the floor for long periods strains joints, and people need a shared space to talk, rest together, or take in the same information at once.",
    has: ["sofa", "television", "bookshelf", "coffee table"],
  },
  {
    slug: "sofa",
    name: "Sofa",
    what: "Cushioned seating built for more than one person at once.",
    why: "Sitting on the floor for long stretches strains hips and backs. Shared, cushioned seating supports the body and keeps people facing each other to talk.",
    has: ["cushions", "sofa frame", "upholstery"],
  },
  {
    slug: "cushions",
    name: "Cushions",
    what: "The soft, removable pads humans sit or lean against on a sofa.",
    why: "A bare rigid frame is uncomfortable to sit on for any length of time. Cushions distribute weight and absorb pressure, the same job a mattress does for lying down.",
    has: ["foam", "fabric"],
  },
  {
    slug: "sofa-frame",
    name: "Sofa Frame",
    what: "The rigid internal structure a sofa's cushions and upholstery are built around.",
    why: "It has to hold the sofa's shape and bear repeated sitting weight without sagging or collapsing over years of daily use.",
    has: ["wood"],
  },
  {
    slug: "upholstery",
    name: "Upholstery",
    what: "The fabric or leather covering stretched over a sofa's frame and cushions.",
    why: "It protects the padding underneath from wear and dirt while giving the sofa a surface that's comfortable to touch and easy to clean.",
    has: ["fabric"],
  },
  {
    slug: "television",
    name: "Television",
    what: "A screen and speaker that display moving images and sound.",
    why: "It gives a household shared access to information and entertainment without anyone having to travel to get it.",
    has: ["screen", "speaker", "remote"],
  },
  {
    slug: "screen",
    name: "Screen",
    what: "The panel that displays the image, made of many individually lit or shuttered pixels.",
    why: "It's what actually renders the picture — the rest of the television exists only to receive, process, and power what appears here.",
    has: ["pixels", "glass"],
  },
  {
    slug: "pixels",
    name: "Pixels",
    what: "The smallest individually controllable points of light that together form a displayed image.",
    why: "No single light source could reproduce a detailed picture. Splitting the image into thousands of tiny, independently lit points is what makes arbitrary images possible at all.",
    has: [],
  },
  {
    slug: "speaker",
    name: "Speaker",
    what: "A component that converts electrical signal into sound.",
    why: "A moving picture without sound loses dialogue, music, and cues. The speaker is what makes the television carry more than half the story.",
    has: ["diaphragm", "magnet"],
  },
  {
    slug: "diaphragm",
    name: "Diaphragm",
    what: "A thin, flexible cone or membrane that vibrates to push air and create sound waves.",
    why: "Sound is just moving air. The diaphragm is the physical surface that actually does the moving, translating electrical signal into audible pressure waves.",
    has: [],
  },
  {
    slug: "magnet",
    name: "Magnet",
    what: "A component that creates a magnetic field, used in a speaker to drive the diaphragm's motion.",
    why: "A coil carrying varying current sits next to the magnet and gets pushed and pulled as that current changes, and that motion is what drives the diaphragm.",
    has: [],
  },
  {
    slug: "remote",
    name: "Remote",
    what: "A handheld wireless control for the television.",
    why: "Getting up to change every channel or adjust the volume would defeat the point of relaxing in front of the screen. The remote lets that happen from the seat.",
    has: ["infrared LED", "buttons"],
  },
  {
    slug: "infrared-led",
    name: "Infrared LED",
    what: "A small component that emits invisible infrared light in coded pulses.",
    why: "It's the actual signal carrier — the television reads the pattern of pulses as a specific command, all without any wired connection between the two.",
    has: [],
  },
  {
    slug: "buttons",
    name: "Buttons",
    what: "Physical switches on a remote's surface, each mapped to a specific command.",
    why: "They give a fast, tactile way to select a command by feel, without looking away from the screen to find it.",
    has: [],
  },
  {
    slug: "bookshelf",
    name: "Bookshelf",
    what: "A shelving unit for storing books upright and in order.",
    why: "Books pile up and get damaged or lost if left loose. Shelving keeps them protected, visible, and easy to find again.",
    has: ["bookshelf shelves", "bookshelf frame"],
  },
  {
    slug: "bookshelf-shelves",
    name: "Bookshelf Shelves",
    what: "The horizontal boards a bookshelf is built from, spaced to hold books upright.",
    why: "Books need a flat, level surface to stand on so their spines stay visible instead of toppling sideways into a pile.",
    has: ["wood"],
  },
  {
    slug: "bookshelf-frame",
    name: "Bookshelf Frame",
    what: "The vertical sides and back that hold a bookshelf's boards in place and bear their weight.",
    why: "Without a rigid frame around them, the shelf boards would flex, tip, or spread apart under the weight of the books stacked on them.",
    has: ["wood"],
  },
  {
    slug: "coffee-table",
    name: "Coffee Table",
    what: "A low table positioned in front of a sofa, within reach of seated people.",
    why: "People sitting need a nearby surface for drinks, remotes, or books without getting up. A full-height table would sit above where someone reclining could comfortably reach.",
    has: ["tabletop", "legs"],
  },
  {
    slug: "tabletop",
    name: "Tabletop",
    what: "The flat horizontal surface of a table, fixed on top of its legs.",
    why: "A table's function lives entirely in this flat surface — everything else exists just to hold it at a usable height.",
    has: ["wood"],
  },
];
