import type { Artifact } from "./types";

// Shared raw materials and generic hardware, reused across multiple rooms/branches.
export const materials: Artifact[] = [
  {
    slug: "polymer",
    name: "Polymer",
    what: "A synthetic material made of long, repeating molecular chains.",
    why: "Long, repeating chains give it a broad, tunable range of properties — flexible and elastic or rigid and impact-resistant — depending on how the chains are built and linked. That range is why it shows up in foam, grips, and structural parts alike.",
    has: ["monomer", "chain bond"],
  },
  {
    slug: "monomer",
    name: "Monomer",
    what: "A single small molecule that repeats to build a polymer chain.",
    why: "Linking identical units end to end gives the chain uniform, predictable properties. Change the monomer and you change how stretchy, dense, or heat-resistant the resulting polymer is.",
    has: ["carbon", "hydrogen", "oxygen"],
  },
  {
    slug: "chain-bond",
    name: "Chain Bond",
    what: "The covalent bond connecting one monomer to the next along the chain.",
    why: "A strong link is what keeps the chain from snapping apart as it's stretched and released thousands of times. Weak bonds would mean a material that degrades after a few uses.",
    has: [],
  },
  {
    slug: "drain",
    name: "Drain",
    what: "An opening connected to a pipe that carries used water away.",
    why: "Without an outlet, a basin, bowl, or shower floor would just fill up and overflow instead of clearing used water so more can be used.",
    has: ["trap"],
  },
  {
    slug: "faucet",
    name: "Faucet",
    what: "A fixture that controls the flow and temperature of water from the plumbing.",
    why: "Plumbing alone is just an always-on pipe. A faucet lets a person start, stop, and mix hot and cold water on demand instead of an uncontrolled flow.",
    has: ["valve"],
  },
  {
    slug: "fabric",
    name: "Fabric",
    what: "Woven or knit cloth made from interlocking fibers.",
    why: "Loose fibers on their own are just dust or thread. Weaving or knitting them together creates a flexible sheet that's both durable and easy to shape around objects.",
    has: [],
  },
  {
    slug: "steel",
    name: "Steel",
    what: "An alloy of iron with a small, controlled amount of carbon.",
    why: "Pure iron is too soft to hold an edge and too prone to rust. Adding carbon and hardening it lets steel stay sharp, rigid, or springy far longer than iron alone.",
    has: [],
  },
  {
    slug: "rivets",
    name: "Rivets",
    what: "Short metal pins that clamp two flat parts together through matching holes.",
    why: "Glue can fail under repeated flexing and screws can back out over time. A rivet's deformed head can't loosen on its own, which matters on a part gripped and twisted constantly.",
    has: [],
  },
  {
    slug: "ceramic",
    name: "Ceramic",
    what: "A hard, heat-resistant material made by firing mineral compounds at high temperature.",
    why: "It tolerates direct, repeated high heat without warping, cracking from thermal shock, or reacting with food or water — something most metals and all plastics can't do.",
    has: [],
  },
  {
    slug: "glass",
    name: "Glass",
    what: "A hard, transparent material made by melting and rapidly cooling silica-based minerals.",
    why: "Its transparency lets what's behind it stay visible without opening or exposing it, and its hardness resists most everyday scratches and spills.",
    has: [],
  },
  {
    slug: "wire",
    name: "Wire",
    what: "Metal drawn out into a thin, flexible strand.",
    why: "Shaped into a grid or coil it holds weight or carries current like a solid piece would, while staying light and letting air or light pass through the gaps.",
    has: [],
  },
  {
    slug: "wood",
    name: "Wood",
    what: "The fibrous structural material from a tree's trunk and branches, cut and dried for building.",
    why: "It's strong along its grain relative to its weight, easy to shape with hand tools, and doesn't conduct heat or cold the way metal does.",
    has: [],
  },
  {
    slug: "hinges",
    name: "Hinges",
    what: "A jointed metal fitting that lets one panel pivot against a fixed frame.",
    why: "Without a pivot point, a panel would have to be lifted fully in and out rather than swinging open and closed in place.",
    has: [],
  },
  {
    slug: "trap",
    name: "Trap",
    what: "A curved section of pipe just below a drain that stays filled with water.",
    why: "That trapped water blocks sewer gas from rising back up through the drain, the same job a toilet bowl's standing water does for the room it sits in.",
    has: [],
  },
  {
    slug: "valve",
    name: "Valve",
    what: "A mechanism inside a faucet that opens or restricts the path water flows through.",
    why: "Turning a handle needs to translate into more or less water actually passing through. The valve is the part doing that restriction.",
    has: [],
  },
  {
    slug: "carbon",
    name: "Carbon",
    what: "An atom with four bonding sites, able to link to other carbon atoms in long chains and rings.",
    why: "That four-way bonding capacity is what lets it form the long, stable backbones every organic polymer chain is built on — nothing else bonds as flexibly or as strongly with itself.",
    has: [],
  },
  {
    slug: "hydrogen",
    name: "Hydrogen",
    what: "The smallest, lightest atom, usually bonded along a polymer's carbon backbone.",
    why: "It fills the remaining bonding sites along the chain, and how many attach where is part of what shapes the chain's flexibility and weight.",
    has: [],
  },
  {
    slug: "oxygen",
    name: "Oxygen",
    what: "An atom that bonds readily with carbon and hydrogen, often bridging or capping a chain.",
    why: "Placing oxygen at specific points along the backbone creates reactive sites chemists use to control how and where chains link, stretch, or eventually break down.",
    has: [],
  },
  {
    slug: "cardboard",
    name: "Cardboard",
    what: "A stiff, layered paper material with a corrugated inner layer for strength.",
    why: "Flat paper alone bends and tears under any real weight. A corrugated ridge sandwiched between two flat sheets holds a rigid shape while staying light and cheap to produce in bulk.",
    has: [],
  },
  {
    slug: "rubber",
    name: "Rubber",
    what: "A flexible, grippy material that resists sliding even when wet.",
    why: "It deforms slightly against a surface without sliding, unlike smooth plastic or fabric alone — that grip is what keeps a mat or seal in place under pressure or moisture.",
    has: [],
  },
];
