import type { Artifact } from "./types";

// Shared raw materials and generic hardware, reused across multiple rooms/branches.
export const materials: Artifact[] = [
  {
    slug: "polymer",
    name: "Polymer",
    what: "A synthetic material made of long, repeating molecular chains.",
    why: "Long, repeating chains give it a broad, tunable range of properties — flexible and elastic or rigid and impact-resistant — depending on how the chains are built and linked. That range is why it shows up in foam, grips, and structural parts alike.",
    has: ["monomer", "chain bond"],
  },
  {
    slug: "monomer",
    name: "Monomer",
    what: "A single small molecule that repeats to build a polymer chain.",
    why: "Linking identical units end to end gives the chain uniform, predictable properties. Change the monomer and you change how stretchy, dense, or heat-resistant the resulting polymer is.",
    has: ["carbon", "hydrogen", "oxygen"],
  },
  {
    slug: "chain-bond",
    name: "Chain Bond",
    what: "The covalent bond connecting one monomer to the next along the chain.",
    why: "A strong link is what keeps the chain from snapping apart as it's stretched and released thousands of times. Weak bonds would mean a material that degrades after a few uses.",
    has: [],
  },
  {
    slug: "drain",
    name: "Drain",
    what: "An opening connected to a pipe that carries used water away.",
    why: "Without an outlet, a basin, bowl, or shower floor would just fill up and overflow instead of clearing used water so more can be used.",
    has: ["trap"],
  },
  {
    slug: "faucet",
    name: "Faucet",
    what: "A fixture that controls the flow and temperature of water from the plumbing.",
    why: "Plumbing alone is just an always-on pipe. A faucet lets a person start, stop, and mix hot and cold water on demand instead of an uncontrolled flow.",
    has: ["valve"],
  },
  {
    slug: "fabric",
    name: "Fabric",
    what: "Woven or knit cloth made from interlocking fibers.",
    why: "Loose fibers on their own are just dust or thread. Weaving or knitting them together creates a flexible sheet that's both durable and easy to shape around objects.",
    has: [],
  },
  {
    slug: "steel",
    name: "Steel",
    what: "An alloy of iron with a small, controlled amount of carbon.",
    why: "Pure iron is too soft to hold an edge and too prone to rust. Adding carbon and hardening it lets steel stay sharp, rigid, or springy far longer than iron alone.",
    has: [],
  },
  {
    slug: "rivets",
    name: "Rivets",
    what: "Short metal pins that clamp two flat parts together through matching holes.",
    why: "Glue can fail under repeated flexing and screws can back out over time. A rivet's deformed head can't loosen on its own, which matters on a part gripped and twisted constantly.",
    has: [],
  },
  {
    slug: "ceramic",
    name: "Ceramic",
    what: "A hard, heat-resistant material made by firing mineral compounds at high temperature.",
    why: "It tolerates direct, repeated high heat without warping, cracking from thermal shock, or reacting with food or water — something most metals and all plastics can't do.",
    has: [],
  },
  {
    slug: "glass",
    name: "Glass",
    what: "A hard, transparent material made by melting and rapidly cooling silica-based minerals.",
    why: "Its transparency lets what's behind it stay visible without opening or exposing it, and its hardness resists most everyday scratches and spills.",
    has: [],
  },
  {
    slug: "wire",
    name: "Wire",
    what: "Metal drawn out into a thin, flexible strand.",
    why: "Shaped into a grid or coil it holds weight or carries current like a solid piece would, while staying light and letting air or light pass through the gaps.",
    has: [],
  },
  {
    slug: "wood",
    name: "Wood",
    what: "The fibrous structural material from a tree's trunk and branches, cut and dried for building.",
    why: "It's strong along its grain relative to its weight, easy to shape with hand tools, and doesn't conduct heat or cold the way metal does.",
    has: [],
  },
  {
    slug: "hinges",
    name: "Hinges",
    what: "A jointed metal fitting that lets one panel pivot against a fixed frame.",
    why: "Without a pivot point, a panel would have to be lifted fully in and out rather than swinging open and closed in place.",
    has: [],
  },
  {
    slug: "trap",
    name: "Trap",
    what: "A curved section of pipe just below a drain that stays filled with water.",
    why: "That trapped water blocks sewer gas from rising back up through the drain, the same job a toilet bowl's standing water does for the room it sits in.",
    has: [],
  },
  {
    slug: "valve",
    name: "Valve",
    what: "A mechanism inside a faucet that opens or restricts the path water flows through.",
    why: "Turning a handle needs to translate into more or less water actually passing through. The valve is the part doing that restriction.",
    has: [],
  },
  {
    slug: "carbon",
    name: "Carbon",
    what: "An atom with four bonding sites, able to link to other carbon atoms in long chains and rings.",
    why: "That four-way bonding capacity is what lets it form the long, stable backbones every organic polymer chain is built on — nothing else bonds as flexibly or as strongly with itself.",
    has: [],
  },
  {
    slug: "hydrogen",
    name: "Hydrogen",
    what: "The smallest, lightest atom, usually bonded along a polymer's carbon backbone.",
    why: "It fills the remaining bonding sites along the chain, and how many attach where is part of what shapes the chain's flexibility and weight.",
    has: [],
  },
  {
    slug: "oxygen",
    name: "Oxygen",
    what: "An atom that bonds readily with carbon and hydrogen, often bridging or capping a chain.",
    why: "Placing oxygen at specific points along the backbone creates reactive sites chemists use to control how and where chains link, stretch, or eventually break down.",
    has: [],
  },
  {
    slug: "cardboard",
    name: "Cardboard",
    what: "A stiff, layered paper material with a corrugated inner layer for strength.",
    why: "Flat paper alone bends and tears under any real weight. A corrugated ridge sandwiched between two flat sheets holds a rigid shape while staying light and cheap to produce in bulk.",
    has: [],
  },
  {
    slug: "rubber",
    name: "Rubber",
    what: "A flexible, grippy material that resists sliding even when wet.",
    why: "It deforms slightly against a surface without sliding, unlike smooth plastic or fabric alone — that grip is what keeps a mat or seal in place under pressure or moisture.",
    has: [],
  },
  {
    slug: "thermostat",
    name: "Thermostat",
    what: "A temperature-sensing switch that cuts power to a heating element once its surroundings reach a set temperature.",
    why: "A heating element left running constantly would overheat and waste energy well past the point water or air is already hot enough — sensing the actual temperature and cutting power automatically holds it at a set point instead.",
    has: ["contacts"],
  },
  {
    slug: "chain",
    name: "Chain",
    what: "A series of interlocking metal links, each looped through the next.",
    why: "A single rigid rod can only pull in a straight line — linked loops flex at every joint, letting the whole length bend, coil, and hang under load a solid bar never could.",
    has: ["steel"],
  },
  {
    slug: "cork",
    name: "Cork",
    what: "A lightweight, porous natural material harvested from cork oak bark.",
    why: "Its soft, slightly springy surface grips a pin without splitting or crumbling the way wood or plastic would after being pinned in the same spot over and over.",
    has: [],
  },
  {
    slug: "push-pins",
    name: "Push Pins",
    what: "Small pins with a flat head and short sharp point, pressed by thumb into a soft board.",
    why: "Paper needs to be held flat against a board without tape that would tear it on removal — a thin pin through a corner does that instantly and comes back out just as easily.",
    has: ["steel"],
  },
  {
    slug: "wicker",
    name: "Wicker",
    what: "Thin, flexible strips of natural cane or synthetic fiber, woven into a rigid open pattern.",
    why: "Solid wood swells and cracks in humidity and direct sun — thin woven strips flex slightly and let air pass through, which is why it holds up in sunrooms and other exposed spots wood alone wouldn't.",
    has: [],
  },
  {
    slug: "bronze",
    name: "Bronze",
    what: "An alloy of copper and tin.",
    why: "Pure copper is soft and dulls quickly, but alloying it with tin makes it harder while keeping enough elasticity to ring clearly and resist cracking under repeated impact — which is why it's used for cymbals and bells instead of plain metal.",
    has: [],
  },
  {
    slug: "leather",
    name: "Leather",
    what: "Tanned and treated animal hide, made durable and water-resistant for use in furniture and goods.",
    why: "Raw hide rots and stiffens as it dries — tanning stabilizes the fibers permanently, giving a material that's flexible, durable, and resistant to moisture and stains in a way untreated hide never could be.",
    has: [],
  },
  {
    slug: "rope",
    name: "Rope",
    what: "Multiple strands of fiber twisted or braided together into a single strong, flexible line.",
    why: "A single fiber strand snaps under even light tension — twisting many together lets them share load and grip each other under strain, giving far more combined strength than any one strand alone.",
    has: [],
  },
  {
    slug: "lead",
    name: "Lead",
    what: "A soft, dense, heavy metal element that resists corrosion from acid.",
    why: "Most metals corrode away when soaked in acid for years, but lead reacts with sulfuric acid in a controlled, reversible way — that reversibility is what lets it store and release charge for years instead of just dissolving.",
    has: [],
  },
  {
    slug: "sulfuric-acid",
    name: "Sulfuric Acid",
    what: "A strong, corrosive acid used as the electrolyte inside lead-acid batteries.",
    why: "Lead plates alone can't generate current — an electrolyte has to carry charged ions between them, and sulfuric acid is what reacts with the lead on each plate to actually produce and store that current.",
    has: [],
  },
  {
    slug: "stone",
    name: "Stone",
    what: "Naturally occurring solid rock, cut or left rough for building and paving.",
    why: "It resists weather, fire, and decades of foot traffic in a way wood and most other materials can't — that durability is exactly what a permanent outdoor path or structure needs.",
    has: [],
  },
  {
    slug: "fiberglass",
    name: "Fiberglass",
    what: "A composite of woven glass fibers set in a hardened polymer resin.",
    why: "Glass fiber alone is brittle and frays apart, and resin alone is too soft to hold a shape under load — bonding them together gives a shell that's rigid, watertight, and won't rot or rust the way wood or bare metal hulls do.",
    has: ["glass", "polymer"],
  },
  {
    slug: "aluminum",
    name: "Aluminum",
    what: "A lightweight, silvery metal that conducts heat quickly.",
    why: "It heats up and cools down far faster than heavier metals like steel or cast iron, so cookware made from it responds almost instantly when a burner's heat is turned up or down instead of lagging behind the adjustment.",
    has: [],
  },
];
