import type { Artifact } from "./types";

export const musicRoom: Artifact[] = [
  {
    slug: "music-room",
    name: "Music Room",
    what: "A room set aside for playing and practicing musical instruments.",
    why: "Instruments are loud and practicing means repeating the same phrase badly many times before it's right — a room set apart lets that noise and repetition happen without disturbing the rest of the house.",
    has: ["piano", "guitar", "drum kit", "music stand", "microphone", "amplifier"],
  },
  {
    slug: "piano",
    name: "Piano",
    what: "A large keyboard instrument that produces sound by hammers striking tensioned strings.",
    why: "A string plucked or struck vibrates at a fixed pitch, and a whole keyboard of them tuned to different pitches lets one performer play full chords and melodies with just their hands, something no single string instrument alone allows.",
    has: ["piano keys", "piano strings", "hammers"],
  },
  {
    slug: "piano-keys",
    name: "Piano Keys",
    what: "The row of black and white levers on a piano that a player presses to trigger each note.",
    why: "Each key is a lever mapped to one specific string or set of strings — pressing it is what translates a finger's motion into a hammer striking that exact pitch.",
    has: ["wood"],
  },
  {
    slug: "piano-strings",
    name: "Piano Strings",
    what: "Tensioned metal wires stretched across a piano's frame, each tuned to a specific pitch.",
    why: "A string's pitch is set by its length, thickness, and tension — dozens of strings each tuned differently is what gives the instrument its full range of notes.",
    has: ["wire"],
  },
  {
    slug: "hammers",
    name: "Hammers",
    what: "Small felt-covered mallets inside a piano that strike a string the instant its key is pressed.",
    why: "A string has to be struck, not just touched, to set it vibrating loud enough to hear — felt padding on the hammer softens that strike into a musical tone instead of a harsh clack.",
    has: ["wood", "felt"],
  },
  {
    slug: "felt",
    name: "Felt",
    what: "A dense, non-woven fabric made by matting fibers together under heat and pressure rather than weaving them.",
    why: "A hard hammer striking a string would produce a harsh, clacking noise — felt's soft, compressible surface cushions that strike into a rounder, more musical tone.",
    has: ["fabric"],
  },
  {
    slug: "guitar",
    name: "Guitar",
    what: "A stringed instrument played by plucking or strumming tensioned strings over a hollow or solid body.",
    why: "Unlike a piano's fixed hammers, a guitar's strings are touched directly by the player's hand, giving far more control over each note's timing, volume, and expression at the cost of only playing one note at a time per string.",
    has: ["guitar strings", "guitar body", "fretboard"],
  },
  {
    slug: "guitar-strings",
    name: "Guitar Strings",
    what: "Tensioned metal or nylon strings stretched along a guitar's neck and body.",
    why: "Like a piano string, its pitch comes from length, thickness, and tension — but here the player's fingers pluck and press it directly rather than a hammer striking it.",
    has: ["wire"],
  },
  {
    slug: "guitar-body",
    name: "Guitar Body",
    what: "The hollow wooden chamber a guitar's strings are mounted across.",
    why: "A plucked string alone is barely audible — the hollow body resonates with the string's vibration and projects it as sound loud enough to hear across a room.",
    has: ["wood"],
  },
  {
    slug: "fretboard",
    name: "Fretboard",
    what: "The long strip along a guitar's neck marked with raised metal frets that a player presses strings against.",
    why: "Pressing a string down against a fret shortens its vibrating length to an exact, repeatable point — frets are what let a player hit a precise pitch reliably instead of guessing where to press.",
    has: ["wood", "frets"],
  },
  {
    slug: "frets",
    name: "Frets",
    what: "Thin raised metal strips embedded across a guitar's fretboard at fixed intervals.",
    why: "Without a hard raised edge to press a string against, a finger alone couldn't reliably stop a string at an exact pitch — frets fix that stopping point precisely, the same note every time.",
    has: ["steel"],
  },
  {
    slug: "drum-kit",
    name: "Drum Kit",
    what: "A set of drums and cymbals arranged around a seated player, played together with sticks and pedals.",
    why: "A single drum gives one pitch and tone — arranging several drums and cymbals within arm's and foot's reach lets one player produce a full rhythmic pattern instead of just a single beat.",
    has: ["cymbals", "drumsticks", "bass drum pedal"],
  },
  {
    slug: "cymbals",
    name: "Cymbals",
    what: "Thin round bronze plates that ring with a sharp, sustained crash when struck.",
    why: "Drums alone give percussive thuds but no bright, cutting accent — a thin metal plate struck edge-on rings out above the rest of the kit to mark a beat or crash.",
    has: ["bronze"],
  },
  {
    slug: "drumsticks",
    name: "Drumsticks",
    what: "A pair of slender wooden sticks used to strike drums and cymbals.",
    why: "A bare hand striking a drumhead repeatedly bruises and can't reach a cymbal cleanly — a stick concentrates the strike into a small hard tip and lets the player reach across the whole kit without moving their whole arm.",
    has: ["wood"],
  },
  {
    slug: "bass-drum-pedal",
    name: "Bass Drum Pedal",
    what: "A foot-operated pedal that swings a beater against the bass drum's head.",
    why: "The bass drum sits flat on the floor and both hands are already busy holding sticks — a foot pedal lets the player keep a steady low beat going without needing a third hand.",
    has: ["spring"],
  },
  {
    slug: "music-stand",
    name: "Music Stand",
    what: "An adjustable-height stand with a tilted rest that holds sheet music at eye level for a standing or seated musician.",
    why: "Sheet music laid flat on a table forces a musician to look down and break their playing position — a stand angled toward the player keeps the page visible without breaking focus on the instrument.",
    has: ["music stand legs", "sheet rest"],
  },
  {
    slug: "music-stand-legs",
    name: "Music Stand Legs",
    what: "The folding tripod legs beneath a music stand that hold it upright at an adjustable height.",
    why: "A stand has to adjust to different players' heights and fold flat to carry between rehearsals — tripod legs with a telescoping center pole do both without needing separate stands for each height.",
    has: ["steel"],
  },
  {
    slug: "sheet-rest",
    name: "Sheet Rest",
    what: "The tilted flat ledge at the top of a music stand that sheet music rests against.",
    why: "Loose sheet music laid flat would slide off or need constant repositioning — the tilted ledge holds pages upright and angled toward the player's eyes at a fixed, readable angle.",
    has: [],
  },
  {
    slug: "microphone",
    name: "Microphone",
    what: "A handheld or stand-mounted device that converts sound waves into an electrical signal for recording or amplification.",
    why: "A voice or instrument alone only carries as far as the room allows — converting the sound into an electrical signal lets it be amplified through speakers or recorded, reaching further or being preserved instead of fading in the air.",
    has: ["diaphragm", "microphone stand"],
  },
  {
    slug: "microphone-stand",
    name: "Microphone Stand",
    what: "An adjustable-height stand with a clip or cradle that holds a microphone steady in front of a performer.",
    why: "Holding a microphone by hand ties up one hand needed for an instrument and picks up handling noise from every small movement — a stand holds it steady at a fixed position instead.",
    has: ["steel"],
  },
  {
    slug: "amplifier",
    name: "Amplifier",
    what: "An electronic device that boosts a weak instrument or microphone signal to a level loud enough to drive a speaker.",
    why: "A guitar pickup or microphone alone generates too weak a signal to move a speaker cone with any real volume — an amplifier boosts that signal's power before it reaches the speaker, which is what actually makes it audible across a room.",
    has: ["speaker", "volume dial"],
  },
];
