import type { Artifact } from "./types";

export const nursery: Artifact[] = [
  {
    slug: "nursery",
    name: "Nursery",
    what: "A room set up for an infant to sleep and be cared for.",
    why: "A newborn needs a controlled, safe sleeping space separate from an adult bed, plus a dedicated surface for the frequent diaper changes and feeding that happen through the day and night.",
    has: ["crib", "changing table", "mobile", "nursery glider", "diaper pail", "baby monitor", "baby scale"],
  },
  {
    slug: "crib",
    name: "Crib",
    what: "An enclosed bed with high slatted sides, sized for an infant to sleep in safely.",
    why: "An infant can't be trusted not to roll or climb out of an open bed, and loose bedding around them is a suffocation risk — closely spaced slats let a caregiver see and reach the baby while keeping them contained.",
    has: ["crib slats", "mattress"],
  },
  {
    slug: "crib-slats",
    name: "Crib Slats",
    what: "Closely spaced vertical bars forming the sides of a crib.",
    why: "The gaps have to be narrow enough that a baby's head can't slip through and get stuck, while still letting air and light pass and a caregiver see in from any angle.",
    has: ["wood"],
  },
  {
    slug: "changing-table",
    name: "Changing Table",
    what: "A raised, padded table used for changing an infant's diaper.",
    why: "Changing a diaper on the floor strains a caregiver's back over dozens of changes a day — a table brings the baby up to waist height, with supplies kept within arm's reach the whole time.",
    has: ["changing pad", "changing table drawer"],
  },
  {
    slug: "changing-pad",
    name: "Changing Pad",
    what: "A waterproof cushioned pad on top of a changing table that the baby lies on.",
    why: "An infant needs a soft, slightly contoured surface to lie still on, and the surface has to be wipeable since it gets soiled repeatedly through the day.",
    has: ["foam", "rubber"],
  },
  {
    slug: "changing-table-drawer",
    name: "Changing Table Drawer",
    what: "A shallow drawer built into a changing table for diapers and wipes.",
    why: "A caregiver's hands are occupied holding the baby steady during a change — supplies stored in a drawer built into the same table stay within one-handed reach instead of across the room.",
    has: ["wood"],
  },
  {
    slug: "mobile",
    name: "Mobile",
    what: "A hanging arrangement of small toys or shapes suspended above a crib that slowly rotates.",
    why: "A newborn's eyes can only focus at short range and are drawn to motion and contrast — a slow-turning mobile within that focal distance gives them something to track and helps develop visual attention.",
    has: ["mobile arm", "polymer"],
  },
  {
    slug: "mobile-arm",
    name: "Mobile Arm",
    what: "A curved arm that clamps to a crib rail and extends the mobile's hanging toys out over the mattress.",
    why: "The toys need to hang centered above where the baby actually lies, not off to the side of the crib — the arm's reach is what positions them there.",
    has: ["steel"],
  },
  {
    slug: "nursery-glider",
    name: "Nursery Glider",
    what: "An upholstered chair on a curved or pivoting base that rocks smoothly back and forth, used for feeding or soothing an infant.",
    why: "A steady rocking motion calms a fussy infant and helps them fall asleep — a glider gives a caregiver a comfortable seat that can keep that motion going through long feedings without needing to stand and bounce.",
    has: ["cushions", "glider base"],
  },
  {
    slug: "glider-base",
    name: "Glider Base",
    what: "The curved or pivoting frame beneath a glider chair that lets its seat rock smoothly forward and back.",
    why: "A chair on flat legs can't rock at all — the base's curved or hinged mechanism converts a small push into smooth, continuous back-and-forth motion instead of leaving a static seat.",
    has: ["wood"],
  },
  {
    slug: "diaper-pail",
    name: "Diaper Pail",
    what: "A sealed, foot-pedal-operated bin specifically for discarding used diapers.",
    why: "A used diaper smells far stronger and faster than regular trash — a dedicated pail with a tighter seal than an open trash bin keeps that odor contained until it's emptied, instead of letting it fill the nursery.",
    has: ["polymer", "foot pedal"],
  },
  {
    slug: "foot-pedal",
    name: "Foot Pedal",
    what: "A pedal at the base of a bin that lifts its lid when pressed, without needing hands.",
    why: "A caregiver's hands are usually full holding a baby or a dirty diaper — a foot pedal opens the lid without needing either hand free, then lets it fall shut again once released.",
    has: ["spring"],
  },
  {
    slug: "baby-monitor",
    name: "Baby Monitor",
    what: "A wireless audio or video device that lets a caregiver listen to or watch a sleeping infant from another room.",
    why: "A caregiver can't stay in the nursery the whole time a baby sleeps, but needs to know immediately if it wakes or needs attention — a monitor carries that sound or picture to wherever the caregiver actually is.",
    has: ["microphone", "speaker"],
  },
  {
    slug: "baby-scale",
    name: "Baby Scale",
    what: "A flat, cradle-shaped scale that weighs an infant lying down, used to track growth.",
    why: "An infant can't stand on a regular platform scale, and growth in the first year is tracked in small increments — a flat cradle shape holds the baby safely still while giving a precise enough reading to catch slow growth or feeding problems early.",
    has: ["load sensor", "display"],
  },
];
