import type { Artifact } from "./types";

export const office: Artifact[] = [
  {
    slug: "office",
    name: "Office",
    what: "A room set up for focused desk work — reading, writing, or using a computer.",
    why: "Concentrated mental work needs a dedicated, quiet surface and seat separate from where people eat or relax, or focus keeps breaking against distraction and bad posture.",
    has: ["desk", "office chair", "computer", "printer", "monitor", "filing cabinet", "bulletin board", "label maker", "stapler", "chair mat", "shredder"],
  },
  {
    slug: "desk",
    name: "Desk",
    what: "A flat-topped table sized and positioned for sitting work, usually with a drawer for supplies.",
    why: "Reading, writing, and typing need a stable surface at the right height for the hands and eyes, with storage nearby for what's actively in use.",
    has: ["tabletop", "drawer"],
  },
  {
    slug: "office-chair",
    name: "Office Chair",
    what: "A chair with an adjustable seat height and wheels, built for sitting at a desk for extended periods.",
    why: "Sitting still at a desk for hours strains the lower back and hips differently than sitting on a sofa — height adjustment and swivel let the body reposition without standing up.",
    has: ["cushions", "wheels"],
  },
  {
    slug: "wheels",
    name: "Wheels",
    what: "Small rollers fixed to the base of a chair that let it roll and swivel across the floor.",
    why: "Reaching for something across the desk means sliding the whole chair, not standing up each time — wheels are what make that a smooth roll instead of a drag.",
    has: [],
  },
  {
    slug: "computer",
    name: "Computer",
    what: "An electronic device for processing and displaying digital information, used for work at a desk.",
    why: "Most desk work today is digital — writing, calculating, and communicating happen faster and more flexibly on a screen than on paper.",
    has: ["screen", "keyboard", "mouse"],
  },
  {
    slug: "keyboard",
    name: "Keyboard",
    what: "A grid of mechanical buttons, each mapped to a character or command, used to enter text and instructions.",
    why: "Typing requires converting a huge set of discrete symbols into signals a computer can process — dedicated keys, one per symbol, are faster and more reliable than any other manual input method devised so far.",
    has: ["buttons"],
  },
  {
    slug: "mouse",
    name: "Mouse",
    what: "A handheld pointing device that translates its movement across a surface into cursor movement on screen.",
    why: "A keyboard can trigger commands and enter text but can't point at an arbitrary spot on screen — the mouse gives direct, continuous control over an on-screen cursor for anything not tied to a fixed key.",
    has: ["sensor", "buttons", "scroll wheel"],
  },
  {
    slug: "sensor",
    name: "Sensor",
    what: "A small optical or laser component on the underside of a mouse that detects motion across a surface.",
    why: "Something has to actually measure how far and which direction the mouse moves. The sensor takes rapid snapshots of the surface beneath it and calculates the displacement between them.",
    has: [],
  },
  {
    slug: "scroll-wheel",
    name: "Scroll Wheel",
    what: "A small notched wheel set between a mouse's buttons that spins to scroll a page or list.",
    why: "Scrolling by dragging a page's edge is slow and pulls attention away from the cursor. A wheel under the fingertip lets a person scroll continuously without moving the hand off the mouse at all.",
    has: ["detents"],
  },
  {
    slug: "printer",
    name: "Printer",
    what: "A device that transfers digital text or images onto paper using ink or toner.",
    why: "Reading and signing long documents, or handing someone a physical copy, still works better on paper than a screen for many tasks — a printer turns a digital file into that physical copy on demand.",
    has: ["print head", "toner cartridge", "paper tray"],
  },
  {
    slug: "print-head",
    name: "Print Head",
    what: "A row of tiny nozzles or pins that deposit ink or toner onto paper in a precise pattern as it passes beneath.",
    why: "Text and images are made of thousands of individual dots — the print head is what actually places each one exactly where the digital file specifies.",
    has: [],
  },
  {
    slug: "toner-cartridge",
    name: "Toner Cartridge",
    what: "A sealed cartridge holding powdered or liquid ink that supplies a printer's print head.",
    why: "Ink or toner runs out with use and needs to be replaceable without replacing the whole printer — a sealed cartridge lets that supply be swapped in seconds.",
    has: ["polymer"],
  },
  {
    slug: "paper-tray",
    name: "Paper Tray",
    what: "A tray that holds a stack of blank paper and feeds one sheet at a time into the printer.",
    why: "Paper has to be fed one sheet at a time exactly when needed, not by hand for every page — the tray holds a ready stack and a roller pulls sheets off it automatically.",
    has: ["polymer"],
  },
  {
    slug: "monitor",
    name: "Monitor",
    what: "A standalone display connected to a computer for viewing its output.",
    why: "A laptop's built-in screen is small and fixed at one angle — a separate monitor gives a bigger, adjustable display suited to sitting at a desk for long stretches.",
    has: ["screen", "monitor stand"],
  },
  {
    slug: "monitor-stand",
    name: "Monitor Stand",
    what: "An adjustable base that holds a monitor upright and lets its height and tilt be adjusted.",
    why: "A screen fixed at the wrong height forces the neck to bend for hours at a desk — an adjustable stand lets it be leveled to eye height instead.",
    has: ["steel"],
  },
  {
    slug: "filing-cabinet",
    name: "Filing Cabinet",
    what: "A cabinet with drawers sized to hold hanging file folders of paper documents.",
    why: "Loose papers get lost, damaged, or out of order fast — a drawer sized and slotted for hanging folders keeps documents upright, separated by category, and quick to find again.",
    has: ["file drawer", "steel"],
  },
  {
    slug: "file-drawer",
    name: "File Drawer",
    what: "A deep metal drawer inside a filing cabinet fitted with rails that hanging folders hook onto.",
    why: "Paper folders standing loose in a drawer slump and mix together — rails let each folder hang independently upright, keeping them separated and easy to flip through.",
    has: ["steel", "drawer slide"],
  },
  {
    slug: "bulletin-board",
    name: "Bulletin Board",
    what: "A board mounted on an office wall with a soft surface for pinning notes, memos, and reminders.",
    why: "Loose papers on a desk get buried or lost — pinning a note to a board mounted at eye level keeps it visible without digging through a stack every time.",
    has: ["cork", "push pins"],
  },
  {
    slug: "label-maker",
    name: "Label Maker",
    what: "A small handheld device that prints adhesive-backed labels on demand.",
    why: "Handwritten labels on file folders and boxes fade and get inconsistent between people — a printed label prints crisp, uniform text every time, sticking permanently to whatever it's applied to.",
    has: ["polymer"],
  },
  {
    slug: "stapler",
    name: "Stapler",
    what: "A handheld device that drives a bent metal staple through stacked papers to bind them together.",
    why: "A paper clip only holds pages loosely and slips off — a driven staple physically pierces and folds through every sheet, binding them permanently until it's deliberately removed.",
    has: ["steel", "spring"],
  },
  {
    slug: "chair-mat",
    name: "Chair Mat",
    what: "A thin protective mat placed under an office chair's wheels to protect the floor and let it roll smoothly.",
    why: "Wheeled chair casters dig into carpet and scratch hard flooring over thousands of rolls back and forth — a smooth mat underneath takes that wear instead of the floor itself.",
    has: ["polymer"],
  },
  {
    slug: "shredder",
    name: "Shredder",
    what: "A device that cuts sheets of paper into narrow strips or fine confetti as they're fed through it.",
    why: "A document with an account number or signature can still be read if it's thrown out whole — cutting it into many thin strips makes piecing it back together impractical enough to dispose of it safely.",
    has: ["shredder blades", "motor", "shredder bin"],
  },
  {
    slug: "shredder-blades",
    name: "Shredder Blades",
    what: "A stack of interlocking rotating discs with sharp teeth that pull paper between them and cut it into strips.",
    why: "A single blade only slices along one line, but a sheet fed in continuously needs many parallel cuts made at once — interlocking discs mesh like gears, catching and shearing the whole width of the sheet in one continuous pass.",
    has: ["steel"],
  },
  {
    slug: "shredder-bin",
    name: "Shredder Bin",
    what: "A pull-out container beneath the cutting mechanism that catches the shredded paper strips.",
    why: "Cut paper has nowhere to go once it drops free of the blades — a bin directly underneath catches the strips so it can be carried to the trash and emptied instead of scattering across the floor.",
    has: ["polymer"],
  },
];
