import type { Artifact } from "./types";

export const playroom: Artifact[] = [
  {
    slug: "playroom",
    name: "Playroom",
    what: "A room set aside for children to play, filled with toys and low, kid-scaled furniture.",
    why: "Toys scattered through the rest of the house create clutter and trip hazards in shared spaces — a dedicated room lets play spread out and stay messy without disrupting the rest of the home.",
    has: ["toy chest", "building blocks", "rocking horse", "art easel", "dollhouse", "puzzle", "coloring books"],
  },
  {
    slug: "toy-chest",
    name: "Toy Chest",
    what: "A large lidded box for storing toys, sized to hold many at once.",
    why: "Toys left scattered across the floor are a constant trip hazard and take longer to find in a pile — a single chest gives one place to sweep everything into at the end of the day.",
    has: ["wood", "hinges"],
  },
  {
    slug: "building-blocks",
    name: "Building Blocks",
    what: "Small interlocking or stackable blocks that children arrange into towers and shapes.",
    why: "A child's hands and mind develop fine motor control and spatial reasoning through repeated stacking and fitting — blocks give that practice through open-ended play with no fixed outcome.",
    has: ["polymer"],
  },
  {
    slug: "rocking-horse",
    name: "Rocking Horse",
    what: "A horse-shaped toy mounted on curved rockers that a child sits on and rocks back and forth.",
    why: "Rhythmic rocking motion is soothing and builds a toddler's balance and core strength — a fixed horse shape gives that motion a focused, safe outlet instead of climbing on unstable furniture.",
    has: ["rockers", "wood"],
  },
  {
    slug: "rockers",
    name: "Rockers",
    what: "The two curved wooden runners under a rocking horse that let it tip forward and back.",
    why: "A flat base wouldn't move at all — the curve is what converts a child's shifting weight into the back-and-forth rocking motion.",
    has: ["wood"],
  },
  {
    slug: "art-easel",
    name: "Art Easel",
    what: "A freestanding frame that holds a drawing pad or canvas upright at a child's working height.",
    why: "Drawing flat on a table strains a child's neck looking down and limits the paper to table size — an upright easel holds the surface at eye level and lets them work with their whole arm instead of just their wrist.",
    has: ["easel legs", "tray"],
  },
  {
    slug: "easel-legs",
    name: "Easel Legs",
    what: "The tripod of wooden legs that holds an easel's frame upright and stable.",
    why: "A flat board propped against nothing would slide or tip the moment it's pressed on while drawing — three splayed legs give it a stable stance that resists being pushed over.",
    has: ["wood"],
  },
  {
    slug: "tray",
    name: "Tray",
    what: "A narrow ledge across the base of an easel's frame that holds markers, chalk, or a paper pad in place.",
    why: "Loose supplies set on the floor are constantly out of reach mid-drawing — a ledge right at the base keeps them within arm's reach without a child leaving the easel to grab them.",
    has: [],
  },
  {
    slug: "dollhouse",
    name: "Dollhouse",
    what: "A miniature model house with removable walls or an open front, furnished at small scale for imaginative play.",
    why: "Children rehearse and make sense of real-world scenes — family routines, room layouts — through small-scale, controllable pretend play; a dollhouse gives them a fixed miniature world to act those scenes out in instead of just imagining it.",
    has: ["wood", "miniature furniture"],
  },
  {
    slug: "miniature-furniture",
    name: "Miniature Furniture",
    what: "Small-scale replicas of household furniture, sized to fit inside a dollhouse.",
    why: "A dollhouse's rooms need something to arrange and rearrange for the play to feel like a real home — tiny furniture gives a child that same room-by-room detail an empty box wouldn't.",
    has: ["polymer"],
  },
  {
    slug: "puzzle",
    name: "Puzzle",
    what: "A set of interlocking cardboard pieces that fit together to form a picture.",
    why: "Assembling scattered pieces into one correct picture trains a child's pattern recognition and patience in a way that has a clear, verifiable end state — unlike open-ended play, a puzzle is done when it's done.",
    has: ["cardboard"],
  },
  {
    slug: "coloring-books",
    name: "Coloring Books",
    what: "Bound books of line-drawn pictures meant to be filled in with crayon or marker.",
    why: "A blank page overwhelms a young child with too many choices about what to draw — a pre-drawn outline gives a bounded, achievable task: stay inside the lines, instead of starting from nothing.",
    has: [],
  },
];
