import type { Artifact } from "./types";

export const workshop: Artifact[] = [
  {
    slug: "workshop",
    name: "Workshop",
    what: "A room or dedicated space equipped for building, repairing, and crafting with tools beyond a garage's general storage.",
    why: "Detailed woodworking and repair work needs stationary power tools bolted in place and a layout built around them — cramming that equipment into a garage shared with a parked car limits what can be safely set up and left running mid-project.",
    has: ["table saw", "vise", "dust collector", "power drill", "hand saw", "safety glasses"],
  },
  {
    slug: "table-saw",
    name: "Table Saw",
    what: "A stationary power saw with a circular blade that protrudes up through a flat table, used to make long, straight cuts in wood.",
    why: "A handheld saw drifts off a straight line over a long cut — feeding wood across a fixed blade set into a flat table keeps the cut perfectly straight and repeatable every time.",
    has: ["saw blade", "motor"],
  },
  {
    slug: "saw-blade",
    name: "Saw Blade",
    what: "A toothed steel disc that spins at high speed to cut through wood as it's fed across the table.",
    why: "A smooth blade would burn and push through wood rather than cutting it — evenly spaced teeth each shave off a small chip as they pass, together removing a clean channel of material many times a second.",
    has: ["steel"],
  },
  {
    slug: "vise",
    name: "Vise",
    what: "A clamping tool bolted to a workbench with two jaws that tighten to hold a workpiece steady.",
    why: "Cutting, drilling, or sanding something held only by hand risks it slipping or the tool jumping — clamping it rigidly in a vise frees both hands and keeps the work from moving under tool pressure.",
    has: ["vise jaws", "vise screw"],
  },
  {
    slug: "vise-jaws",
    name: "Vise Jaws",
    what: "The two flat metal faces of a vise that close together to grip a workpiece between them.",
    why: "A single point of contact would let a workpiece rotate or slip under pressure — two parallel faces closing evenly on both sides pin it in place without denting it unevenly.",
    has: ["steel"],
  },
  {
    slug: "vise-screw",
    name: "Vise Screw",
    what: "A threaded rod through a vise's body that a handle turns to draw the jaws together.",
    why: "Turning the handle needs to translate into a slow, powerful clamping force — a screw thread converts that rotation into just that, tightening gradually with far more force than a hand could apply directly.",
    has: ["steel"],
  },
  {
    slug: "dust-collector",
    name: "Dust Collector",
    what: "A powered vacuum system connected to workshop tools that pulls sawdust away from a cut as it's made.",
    why: "Sawdust thrown off a spinning blade builds up fast, gets into machinery, and is a health hazard to breathe over repeated sessions — pulling it away right at the cut keeps it from ever settling into the air or under the tools.",
    has: ["motor", "collection bag"],
  },
  {
    slug: "collection-bag",
    name: "Collection Bag",
    what: "A cloth bag on a dust collector that traps captured sawdust for disposal.",
    why: "The vacuumed sawdust has to end up somewhere instead of just blowing back out — a bag catches and holds it in one place until it's emptied instead of it settling right back onto the floor.",
    has: ["fabric"],
  },
  {
    slug: "power-drill",
    name: "Power Drill",
    what: "A handheld motorized tool that spins a bit to bore holes or drive screws.",
    why: "Turning a screw or boring a hole by hand with a manual driver is slow and tiring over more than a few — a motor spinning the bit does the same work in seconds and with far more consistent force.",
    has: ["drill bit", "motor", "trigger"],
  },
  {
    slug: "drill-bit",
    name: "Drill Bit",
    what: "A hardened, spiral-fluted metal shaft that a drill spins to cut into wood or metal.",
    why: "The spinning motion alone doesn't remove material — the spiral flutes are shaped to cut into the surface at the tip and carry the loosened shavings back up and out of the hole as it deepens.",
    has: ["steel"],
  },
  {
    slug: "trigger",
    name: "Trigger",
    what: "A spring-loaded lever under a drill's grip that switches the motor on when squeezed.",
    why: "A drill needs to spin only while actively in use, not constantly — a trigger under the same finger already gripping the tool starts and stops it instantly without a separate switch to reach for.",
    has: ["spring", "contacts"],
  },
  {
    slug: "hand-saw",
    name: "Hand Saw",
    what: "A handheld saw with a toothed blade for cutting wood without power.",
    why: "Not every cut needs the table saw's power or setup — a hand saw is quick to grab for a single quick cut or for tight spots the table saw can't reach.",
    has: ["saw blade", "handle"],
  },
  {
    slug: "safety-glasses",
    name: "Safety Glasses",
    what: "Clear protective eyewear worn to shield the eyes from flying debris and dust while using power tools.",
    why: "A spinning blade or drill throws small chips and dust at high speed, and eyes have no natural defense against that at close range — a clear shield in front of them blocks debris while still letting the wearer see clearly.",
    has: ["polymer"],
  },
];
