import type { Artifact } from "./types";

export const yard: Artifact[] = [
  {
    slug: "yard",
    name: "Yard",
    what: "The open outdoor ground surrounding a house, usually planted with grass or plants.",
    why: "Weather and rooting plants need open, uncovered ground. The yard is what gives a house room to grow food or lawn, dry laundry, or let people and pets be outside without leaving the property.",
    has: ["lawn", "fence", "garden hose", "mailbox", "grill", "patio furniture"],
  },
  {
    slug: "lawn",
    name: "Lawn",
    what: "An area of the yard planted with a dense, mowed grass groundcover.",
    why: "Bare dirt turns to mud in rain and dust in dry weather. A dense mowed grass layer holds the soil in place and gives a soft, even surface to walk or sit on.",
    has: [],
  },
  {
    slug: "fence",
    name: "Fence",
    what: "A barrier of posts and panels marking a yard's boundary.",
    why: "Property lines need a physical boundary for privacy and to keep pets, kids, or intruders from wandering across them uncontrolled.",
    has: ["wood", "steel"],
  },
  {
    slug: "garden-hose",
    name: "Garden Hose",
    what: "A long flexible tube connected to an outdoor faucet for watering plants or washing things down.",
    why: "Carrying water by hand in buckets across a yard is slow and limited. A hose delivers a continuous stream exactly where it's needed, as far as its length reaches.",
    has: ["rubber", "faucet"],
  },
  {
    slug: "mailbox",
    name: "Mailbox",
    what: "A small lidded box mounted near the street or front door for receiving mail.",
    why: "Mail carriers need a consistent, weatherproof drop-off point that doesn't require anyone to be home — a fixed box at the property's edge gives them that without deliveries piling up exposed to rain.",
    has: ["mailbox door", "post"],
  },
  {
    slug: "mailbox-door",
    name: "Mailbox Door",
    what: "A small hinged flap on the front of a mailbox that swings open to deposit or retrieve mail.",
    why: "Mail needs to go in and be pulled out without exposing the whole box's contents to weather between visits — a small flap keeps the opening covered except for the moment it's used.",
    has: ["steel"],
  },
  {
    slug: "post",
    name: "Post",
    what: "A vertical wooden or metal pole that a mailbox is mounted on at a fixed height by the street.",
    why: "The box needs to sit at a consistent height a mail carrier can reach from a vehicle without leaning out or getting down — a fixed post holds it there permanently.",
    has: ["wood"],
  },
  {
    slug: "grill",
    name: "Grill",
    what: "An outdoor cooking appliance that cooks food over direct heat from gas flame or burning charcoal.",
    why: "Cooking meat and vegetables outside keeps smoke, grease spatter, and heat out of the kitchen, and direct flame contact sears food in a way an indoor stove's pan can't replicate.",
    has: ["grill grate", "burner"],
  },
  {
    slug: "grill-grate",
    name: "Grill Grate",
    what: "A framework of parallel metal bars that food rests directly on above a grill's heat source.",
    why: "Food needs direct contact with a hot surface to sear, while still letting fat drip away and flame or smoke reach it from below — a grate does both, unlike a solid pan that would trap grease and block direct flame contact.",
    has: ["steel"],
  },
  {
    slug: "patio-furniture",
    name: "Patio Furniture",
    what: "Weather-resistant chairs and a table set up outside for sitting and eating in the yard.",
    why: "Indoor furniture would warp, rust, or mildew left outside — patio furniture uses weatherproof materials specifically so seating can live outdoors permanently instead of being carried in after each use.",
    has: ["patio chair", "patio table"],
  },
  {
    slug: "patio-chair",
    name: "Patio Chair",
    what: "A chair built from weather-resistant material, meant to stay outdoors.",
    why: "Sitting outside needs the same support a chair gives indoors, but sun, rain, and temperature swings would warp wood or rust untreated steel — weather-resistant material is what lets it live outside year-round.",
    has: ["polymer"],
  },
  {
    slug: "patio-table",
    name: "Patio Table",
    what: "A table built from weather-resistant material, meant to stay outdoors.",
    why: "Food and drinks set outside still need a stable surface — a table built to tolerate sun and rain lets that surface stay outdoors instead of needing to be carried in and out each time.",
    has: ["polymer"],
  },
];
