import type { Artifact } from "./types";

export const yard: Artifact[] = [
  {
    slug: "yard",
    name: "Yard",
    what: "The open outdoor ground surrounding a house, usually planted with grass or plants.",
    why: "Weather and rooting plants need open, uncovered ground. The yard is what gives a house room to grow food or lawn, dry laundry, or let people and pets be outside without leaving the property.",
    has: ["lawn", "fence", "garden hose", "mailbox", "grill", "patio furniture", "bird feeder", "hammock", "wheelbarrow", "clothesline", "fire pit", "trampoline"],
  },
  {
    slug: "lawn",
    name: "Lawn",
    what: "An area of the yard planted with a dense, mowed grass groundcover.",
    why: "Bare dirt turns to mud in rain and dust in dry weather. A dense mowed grass layer holds the soil in place and gives a soft, even surface to walk or sit on.",
    has: [],
  },
  {
    slug: "fence",
    name: "Fence",
    what: "A barrier of posts and panels marking a yard's boundary.",
    why: "Property lines need a physical boundary for privacy and to keep pets, kids, or intruders from wandering across them uncontrolled.",
    has: ["wood", "steel"],
  },
  {
    slug: "garden-hose",
    name: "Garden Hose",
    what: "A long flexible tube connected to an outdoor faucet for watering plants or washing things down.",
    why: "Carrying water by hand in buckets across a yard is slow and limited. A hose delivers a continuous stream exactly where it's needed, as far as its length reaches.",
    has: ["rubber", "faucet"],
  },
  {
    slug: "mailbox",
    name: "Mailbox",
    what: "A small lidded box mounted near the street or front door for receiving mail.",
    why: "Mail carriers need a consistent, weatherproof drop-off point that doesn't require anyone to be home — a fixed box at the property's edge gives them that without deliveries piling up exposed to rain.",
    has: ["mailbox door", "post"],
  },
  {
    slug: "mailbox-door",
    name: "Mailbox Door",
    what: "A small hinged flap on the front of a mailbox that swings open to deposit or retrieve mail.",
    why: "Mail needs to go in and be pulled out without exposing the whole box's contents to weather between visits — a small flap keeps the opening covered except for the moment it's used.",
    has: ["steel"],
  },
  {
    slug: "post",
    name: "Post",
    what: "A vertical wooden or metal pole that a mailbox is mounted on at a fixed height by the street.",
    why: "The box needs to sit at a consistent height a mail carrier can reach from a vehicle without leaning out or getting down — a fixed post holds it there permanently.",
    has: ["wood"],
  },
  {
    slug: "grill",
    name: "Grill",
    what: "An outdoor cooking appliance that cooks food over direct heat from gas flame or burning charcoal.",
    why: "Cooking meat and vegetables outside keeps smoke, grease spatter, and heat out of the kitchen, and direct flame contact sears food in a way an indoor stove's pan can't replicate.",
    has: ["grill grate", "burner"],
  },
  {
    slug: "grill-grate",
    name: "Grill Grate",
    what: "A framework of parallel metal bars that food rests directly on above a grill's heat source.",
    why: "Food needs direct contact with a hot surface to sear, while still letting fat drip away and flame or smoke reach it from below — a grate does both, unlike a solid pan that would trap grease and block direct flame contact.",
    has: ["steel"],
  },
  {
    slug: "patio-furniture",
    name: "Patio Furniture",
    what: "Weather-resistant chairs and a table set up outside for sitting and eating in the yard.",
    why: "Indoor furniture would warp, rust, or mildew left outside — patio furniture uses weatherproof materials specifically so seating can live outdoors permanently instead of being carried in after each use.",
    has: ["patio chair", "patio table"],
  },
  {
    slug: "patio-chair",
    name: "Patio Chair",
    what: "A chair built from weather-resistant material, meant to stay outdoors.",
    why: "Sitting outside needs the same support a chair gives indoors, but sun, rain, and temperature swings would warp wood or rust untreated steel — weather-resistant material is what lets it live outside year-round.",
    has: ["polymer"],
  },
  {
    slug: "patio-table",
    name: "Patio Table",
    what: "A table built from weather-resistant material, meant to stay outdoors.",
    why: "Food and drinks set outside still need a stable surface — a table built to tolerate sun and rain lets that surface stay outdoors instead of needing to be carried in and out each time.",
    has: ["polymer"],
  },
  {
    slug: "bird-feeder",
    name: "Bird Feeder",
    what: "A small hanging or pole-mounted container that holds bird seed for wild birds in the yard.",
    why: "Natural bird food gets scarce in winter or in yards without much wild vegetation — a stocked feeder draws birds in reliably by supplying food they'd otherwise have to search much further for.",
    has: ["feeder tray", "polymer"],
  },
  {
    slug: "feeder-tray",
    name: "Feeder Tray",
    what: "The perforated tray or ledge at the base of a bird feeder that holds seed within reach of a perched bird.",
    why: "Loose seed poured on the ground gets soaked by rain and picked over by rodents — a raised tray keeps it dry and visible only to birds that can perch and reach it.",
    has: [],
  },
  {
    slug: "hammock",
    name: "Hammock",
    what: "A suspended fabric bed hung between two fixed points, used for lounging or napping outdoors.",
    why: "Ground-level seating in a yard puts a person flat against grass, bugs, and uneven dirt — a hammock lifts them into open air, suspended and gently swaying, which a chair or blanket on the ground can't replicate.",
    has: ["fabric", "rope"],
  },
  {
    slug: "wheelbarrow",
    name: "Wheelbarrow",
    what: "A single-wheeled cart with handles, used to haul soil, mulch, or tools around a yard.",
    why: "Carrying a heavy load of soil or tools by hand strains the back and takes multiple trips — a wheelbarrow lets one wheel bear the weight while the handles steer it, moving a full load in a single trip.",
    has: ["steel", "wheels"],
  },
  {
    slug: "clothesline",
    name: "Clothesline",
    what: "A line strung between two posts in a yard, used to hang wet laundry to dry in open air.",
    why: "Air and sun dry clothes for free and leave them smelling different than a machine dryer does — a line strung outdoors gives fabric that direct airflow and sun exposure a dryer's enclosed drum can't replicate.",
    has: ["rope"],
  },
  {
    slug: "fire-pit",
    name: "Fire Pit",
    what: "An outdoor fixture, usually a low steel or stone bowl, that contains a controlled wood or gas fire people gather around.",
    why: "An open fire on bare ground spreads embers and scorches the surrounding grass — a contained ring holds the burn in one place and keeps flames low enough for people to sit safely around it.",
    has: ["fire ring", "spark screen"],
  },
  {
    slug: "fire-ring",
    name: "Fire Ring",
    what: "The circular steel wall that lines a fire pit's basin, containing the fire and radiating heat outward evenly.",
    why: "Fire needs a barrier at its base to keep the burn from spreading sideways into grass or scattering embers — a fixed ring, unlike a bare dug pit, also holds its shape through repeated hard use and years of heat.",
    has: ["steel"],
  },
  {
    slug: "spark-screen",
    name: "Spark Screen",
    what: "A domed metal mesh cover that sits over a fire pit's flames, letting heat and light through while blocking flying embers.",
    why: "Rising heat carries burning embers up and out on drafts of air, which can land on nearby grass or clothing — a fine mesh dome breaks up that draft and catches embers before they clear the pit.",
    has: ["wire"],
  },
  {
    slug: "trampoline",
    name: "Trampoline",
    what: "A taut fabric mat suspended by springs inside a circular steel frame, used for bouncing.",
    why: "A person's own leg muscles can only return so much of a jump's energy — the springs store the force of landing and release it back all at once, launching the jumper higher than they could manage standing on solid ground.",
    has: ["trampoline frame", "trampoline mat", "spring"],
  },
  {
    slug: "trampoline-frame",
    name: "Trampoline Frame",
    what: "A closed ring of bent steel tubing that anchors the springs and holds the mat off the ground.",
    why: "Every spring around the edge pulls inward on landing, and a closed ring is what keeps that pull from collapsing the whole structure — an open set of straight legs couldn't resist the springs pulling against each other.",
    has: ["steel"],
  },
  {
    slug: "trampoline-mat",
    name: "Trampoline Mat",
    what: "A tightly woven, permeable fabric sheet stretched across the frame that jumpers land and bounce on.",
    why: "The mat itself stores almost none of the bounce — it's woven loosely enough that air and rain pass straight through instead of ballooning or pooling, while the springs at its edges do the actual work of returning the jump.",
    has: ["fabric"],
  },
];
