export type Artifact = {
  slug: string;
  name: string;
  what: string;
  why: string;
  has: string[]; // names of parts/contents; if a name's slug matches another artifact, it links there
};

function slugify(name: string): string {
  return name.toLowerCase().replace(/\s+/g, "-");
}

export const artifacts: Artifact[] = [
  {
    slug: "kitchen",
    name: "Kitchen",
    what: "A room where humans prepare, cook, and store food.",
    why: "Raw food is often unsafe or hard to digest. Cooking breaks it down, kills pathogens, and makes more calories available. Storage keeps food from spoiling between meals.",
    has: ["knife", "stove", "refrigerator"],
  },
  {
    slug: "bedroom",
    name: "Bedroom",
    what: "A room where humans sleep and rest.",
    why: "The body and brain need extended, uninterrupted downtime to repair tissue and consolidate memory. A dark, quiet, enclosed space makes that rest possible.",
    has: ["bed", "closet", "lamp"],
  },
  {
    slug: "bathroom",
    name: "Bathroom",
    what: "A room where humans wash and dispose of bodily waste.",
    why: "Waste and unwashed skin both carry pathogens. Containing waste disposal and washing to one plumbed room keeps disease from spreading through the rest of the home.",
    has: ["toilet", "shower", "sink"],
  },
  {
    slug: "living-room",
    name: "Living Room",
    what: "A room where humans gather, relax, and share information.",
    why: "Sitting on the floor for long periods strains joints, and people need a shared space to talk, rest together, or take in the same information at once.",
    has: ["sofa", "television", "bookshelf"],
  },
  {
    slug: "knife",
    name: "Knife",
    what: "A blade fixed to a handle, used to cut food into smaller pieces.",
    why: "Human teeth and hands can't efficiently reduce most raw ingredients to cookable or edible sizes. A knife concentrates force into a thin edge, cutting with far less effort.",
    has: ["blade", "handle", "edge"],
  },
  {
    slug: "stove",
    name: "Stove",
    what: "A controlled heat source for cooking, powered by gas flame or electric element.",
    why: "Cooking requires sustained, adjustable heat. Open fire is hard to control and unsafe indoors; a stove contains the heat and lets it be raised or lowered on demand.",
    has: ["burner", "control knob", "surface"],
  },
  {
    slug: "refrigerator",
    name: "Refrigerator",
    what: "An insulated, mechanically cooled cabinet that keeps food below room temperature.",
    why: "Bacteria multiply fast at room temperature and spoil food within hours or days. Cold slows that growth dramatically, letting food stay safe to eat for days or weeks.",
    has: ["compressor", "insulated cabinet", "refrigerator shelves"],
  },
  {
    slug: "bed",
    name: "Bed",
    what: "A raised, padded surface for lying down and sleeping.",
    why: "Sleeping on bare ground is cold, hard, and uneven, which disturbs sleep and strains joints. Elevation and padding regulate body temperature and cushion pressure points.",
    has: ["mattress", "frame", "pillow"],
  },
  {
    slug: "mattress",
    name: "Mattress",
    what: "A thick, padded cushion filled with foam, springs, or fiber that a person lies on.",
    why: "A bare frame or floor is too hard for sustained contact. Padding spreads body weight evenly, reducing pressure on hips and shoulders so muscles can fully relax.",
    has: ["foam", "cover"],
  },
  {
    slug: "foam",
    name: "Foam",
    what: "A soft, porous material that compresses under weight and springs back.",
    why: "Rigid material would push back evenly hard everywhere. Foam yields more where weight is greatest, letting it cushion hips and shoulders differently from lighter contact points.",
    has: ["polymer", "air cells"],
  },
  {
    slug: "polymer",
    name: "Polymer",
    what: "A synthetic material made of long, repeating molecular chains.",
    why: "Long, repeating chains give it a broad, tunable range of properties — flexible and elastic or rigid and impact-resistant — depending on how the chains are built and linked. That range is why it shows up in foam, grips, and structural parts alike.",
    has: ["monomer", "chain bond"],
  },
  {
    slug: "monomer",
    name: "Monomer",
    what: "A single small molecule that repeats to build a polymer chain.",
    why: "Linking identical units end to end gives the chain uniform, predictable properties. Change the monomer and you change how stretchy, dense, or heat-resistant the resulting polymer is.",
    has: ["carbon", "hydrogen", "oxygen"],
  },
  {
    slug: "chain-bond",
    name: "Chain Bond",
    what: "The covalent bond connecting one monomer to the next along the chain.",
    why: "A strong link is what keeps the chain from snapping apart as it's stretched and released thousands of times. Weak bonds would mean a material that degrades after a few uses.",
    has: [],
  },
  {
    slug: "air-cells",
    name: "Air Cells",
    what: "Tiny pockets of trapped air spread throughout the foam.",
    why: "Air compresses easily, so the cells absorb impact instead of pushing straight back. They also let air move through the foam so heat and moisture don't get trapped against the body.",
    has: ["cell wall", "trapped air"],
  },
  {
    slug: "cell-wall",
    name: "Cell Wall",
    what: "A thin membrane of foam material surrounding each air pocket.",
    why: "It holds each pocket's shape and keeps neighboring cells separate, so pressure in one cell doesn't just leak straight into the next when the foam is compressed.",
    has: [],
  },
  {
    slug: "trapped-air",
    name: "Trapped Air",
    what: "Air sealed inside a cell when the foam was formed.",
    why: "Air resists compression but escapes slowly through the cell walls under pressure. That slow leak-and-refill is what gives foam its gradual give-and-recover feel instead of an instant bounce.",
    has: [],
  },
  {
    slug: "cover",
    name: "Cover",
    what: "A removable fabric layer wrapped around the mattress.",
    why: "The mattress itself absorbs sweat, oil, and dust and can't be washed. A removable cover can be stripped off and cleaned without damaging the foam underneath.",
    has: ["fabric", "stitching"],
  },
  {
    slug: "frame",
    name: "Bed Frame",
    what: "A rigid structure that holds the mattress up off the floor.",
    why: "The floor is cold, drafty, and collects dust and pests. Raising the mattress keeps the sleeper warmer and the sleeping surface cleaner.",
    has: ["legs", "rails"],
  },
  {
    slug: "pillow",
    name: "Pillow",
    what: "A small, soft cushion for supporting the head and neck.",
    why: "Without support, the head tilts and strains the neck and upper spine overnight. A pillow keeps the spine aligned so muscles aren't working while asleep.",
    has: ["filling", "case"],
  },
  {
    slug: "closet",
    name: "Closet",
    what: "An enclosed storage space for clothing.",
    why: "Clothes need to be kept clean, uncrumpled, and out of the way, while still being quick to find and reach for daily.",
    has: ["rod", "closet shelves", "door"],
  },
  {
    slug: "lamp",
    name: "Lamp",
    what: "A portable or fixed source of artificial light.",
    why: "Human eyes can't see without light, and natural light disappears at night. Artificial light lets people keep doing things after the sun sets.",
    has: ["bulb", "shade", "switch"],
  },
  {
    slug: "toilet",
    name: "Toilet",
    what: "A plumbed fixture for disposing of bodily waste with water.",
    why: "Waste carries pathogens and needs to be sealed away and flushed out of living space, not left exposed where it can spread disease.",
    has: ["bowl", "tank", "seat"],
  },
  {
    slug: "shower",
    name: "Shower",
    what: "A fixture that sprays water over the body for washing.",
    why: "Skin builds up oil, sweat, and bacteria over the day. Regular washing removes that buildup, preventing infection, irritation, and odor.",
    has: ["showerhead", "drain", "faucet"],
  },
  {
    slug: "sink",
    name: "Sink",
    what: "A basin with running water for washing hands and face.",
    why: "Hands touch many surfaces and pick up germs constantly. Frequent, quick washing breaks the chain of transmission before it reaches food or the face.",
    has: ["basin", "faucet", "drain"],
  },
  {
    slug: "sofa",
    name: "Sofa",
    what: "Cushioned seating built for more than one person at once.",
    why: "Sitting on the floor for long stretches strains hips and backs. Shared, cushioned seating supports the body and keeps people facing each other to talk.",
    has: ["cushions", "sofa frame", "upholstery"],
  },
  {
    slug: "television",
    name: "Television",
    what: "A screen and speaker that display moving images and sound.",
    why: "It gives a household shared access to information and entertainment without anyone having to travel to get it.",
    has: ["screen", "speaker", "remote"],
  },
  {
    slug: "bookshelf",
    name: "Bookshelf",
    what: "A shelving unit for storing books upright and in order.",
    why: "Books pile up and get damaged or lost if left loose. Shelving keeps them protected, visible, and easy to find again.",
    has: ["bookshelf shelves", "bookshelf frame"],
  },
  {
    slug: "blade",
    name: "Blade",
    what: "The thin, sharpened piece of metal that does the actual cutting.",
    why: "A hardened, narrow edge concentrates force into a small contact area, letting it slice through fibers that a blunt surface would just squash.",
    has: ["steel", "bevel"],
  },
  {
    slug: "handle",
    name: "Handle",
    what: "The grip attached to a blade or tool, shaped to be held by hand.",
    why: "A bare blade against skin would cut the user too. A handle gives a safe, controlled grip so force goes into the material being cut, not the hand.",
    has: ["polymer", "rivets"],
  },
  {
    slug: "edge",
    name: "Edge",
    what: "The extremely thin, sharpened line along a blade where cutting happens.",
    why: "The thinner the edge, the less force is needed to start a cut. Sharpening keeps that edge thin as everyday use gradually wears and rounds it down.",
    has: ["cutting angle", "burr"],
  },
  {
    slug: "burner",
    name: "Burner",
    what: "The individual heating point on a stove — a gas ring or electric coil.",
    why: "Separate burners let multiple pots be heated at different temperatures at the same time, instead of everything sharing one heat source.",
    has: ["gas jet", "igniter"],
  },
  {
    slug: "control-knob",
    name: "Control Knob",
    what: "A rotating dial that adjusts a burner's heat output.",
    why: "Different foods need different heat levels. A knob gives fine, immediate control instead of an all-or-nothing flame.",
    has: ["shaft", "detents"],
  },
  {
    slug: "surface",
    name: "Surface",
    what: "The flat, heat-resistant top a stove's burners sit in.",
    why: "It contains spills and holds pots steady while cooking, keeping heat and mess contained instead of spreading to the rest of the kitchen.",
    has: ["ceramic", "grate"],
  },
  {
    slug: "compressor",
    name: "Compressor",
    what: "A pump that compresses refrigerant gas to move heat out of a cabinet.",
    why: "Cold isn't created directly — heat has to be pumped out from somewhere. The compressor drives that cycle, and that pumping is what actually lowers the internal temperature.",
    has: ["motor", "refrigerant"],
  },
  {
    slug: "insulated-cabinet",
    name: "Insulated Cabinet",
    what: "The outer shell of a refrigerator, lined with insulating material.",
    why: "Without insulation, the cold air inside would constantly trade heat with the warmer room, forcing the compressor to run nonstop just to hold temperature.",
    has: ["insulation", "steel"],
  },
  {
    slug: "refrigerator-shelves",
    name: "Refrigerator Shelves",
    what: "The fixed or adjustable trays inside a refrigerator's cabinet that hold food.",
    why: "Stacking food loose would crush whatever's on the bottom and make anything at the back impossible to reach without unpacking everything above it.",
    has: ["glass", "wire"],
  },
  {
    slug: "legs",
    name: "Legs",
    what: "The vertical supports that raise a frame off the floor.",
    why: "Without legs, a frame would sit flush on the ground, defeating the point of raising the mattress away from the cold, drafty floor.",
    has: ["wood"],
  },
  {
    slug: "rails",
    name: "Rails",
    what: "The horizontal side pieces connecting a frame's ends and supporting the mattress's edges.",
    why: "Without rails, the mattress would sag unsupported along its long sides instead of being held flat and level.",
    has: ["wood"],
  },
  {
    slug: "filling",
    name: "Filling",
    what: "The soft material packed inside a pillow — foam, down, or fiber.",
    why: "It's what actually molds to the shape of the head and neck; without it, the pillow would just be a flat, empty shell offering no support.",
    has: ["down", "fiberfill"],
  },
  {
    slug: "case",
    name: "Case",
    what: "A removable fabric cover around a pillow.",
    why: "Like a mattress cover, it catches oil, sweat, and dust so it can be washed regularly without exposing or wearing out the filling underneath.",
    has: ["fabric", "zipper"],
  },
  {
    slug: "rod",
    name: "Rod",
    what: "A horizontal bar for hanging clothes on hangers.",
    why: "Hanging keeps clothes from creasing the way folding and stacking does, and keeps each item visible and reachable at a glance.",
    has: ["steel"],
  },
  {
    slug: "closet-shelves",
    name: "Closet Shelves",
    what: "Fixed platforms above or beside a closet's hanging rod, for folded items.",
    why: "Not everything hangs well — sweaters and stacks of folded clothing need a flat surface instead of a bar, or they lose their shape.",
    has: ["wood"],
  },
  {
    slug: "door",
    name: "Door",
    what: "A panel that closes off an opening.",
    why: "It keeps what's behind it out of sight and out of the room's dust and light, which would otherwise fade fabric or let clutter spill into the room.",
    has: ["wood", "hinges"],
  },
  {
    slug: "bulb",
    name: "Bulb",
    what: "The component that converts electricity into visible light.",
    why: "It's the actual light source — everything else in a lamp exists just to hold it, power it, or direct where its light goes.",
    has: ["filament", "glass"],
  },
  {
    slug: "shade",
    name: "Shade",
    what: "A cover around a bulb that diffuses and directs its light.",
    why: "A bare bulb glares directly into the eyes. A shade spreads that light out and points it toward where it's actually useful.",
    has: ["fabric", "wire"],
  },
  {
    slug: "switch",
    name: "Switch",
    what: "A mechanism that opens or closes the circuit powering a device.",
    why: "Without a switch, a lamp would either always be off or always be on, wasting power or forcing it to be unplugged just to turn off.",
    has: ["contacts", "spring"],
  },
  {
    slug: "bowl",
    name: "Bowl",
    what: "The water-holding basin of a toilet that receives waste.",
    why: "Standing water in the bowl seals the pipe below it, blocking sewer gas and odor from rising back up into the room.",
    has: ["ceramic"],
  },
  {
    slug: "tank",
    name: "Tank",
    what: "A reservoir that holds water for flushing a toilet.",
    why: "A flush needs a sudden volume of water to clear the bowl and refill its seal. The tank stores that volume, ready to release on demand.",
    has: ["ceramic", "flush valve"],
  },
  {
    slug: "seat",
    name: "Seat",
    what: "The ring humans sit on, hinged to a toilet bowl.",
    why: "It raises and shapes the contact surface for comfort and hygiene, and lifts away for cleaning or alternate use.",
    has: ["polymer", "hinges"],
  },
  {
    slug: "showerhead",
    name: "Showerhead",
    what: "The perforated fixture that turns a water stream into a spray of droplets.",
    why: "A single solid stream wouldn't cover the whole body. Splitting it into many small streams spreads coverage and softens the impact on skin.",
    has: ["nozzles"],
  },
  {
    slug: "drain",
    name: "Drain",
    what: "An opening connected to a pipe that carries used water away.",
    why: "Without an outlet, a basin, bowl, or shower floor would just fill up and overflow instead of clearing used water so more can be used.",
    has: ["trap"],
  },
  {
    slug: "faucet",
    name: "Faucet",
    what: "A fixture that controls the flow and temperature of water from the plumbing.",
    why: "Plumbing alone is just an always-on pipe. A faucet lets a person start, stop, and mix hot and cold water on demand instead of an uncontrolled flow.",
    has: ["valve"],
  },
  {
    slug: "basin",
    name: "Basin",
    what: "The bowl-shaped fixture that holds and channels water while washing.",
    why: "Without a contained basin, washing at a faucet would just splash water everywhere instead of channeling it straight to the drain.",
    has: ["ceramic"],
  },
  {
    slug: "cushions",
    name: "Cushions",
    what: "The soft, removable pads humans sit or lean against on a sofa.",
    why: "A bare rigid frame is uncomfortable to sit on for any length of time. Cushions distribute weight and absorb pressure, the same job a mattress does for lying down.",
    has: ["foam", "fabric"],
  },
  {
    slug: "sofa-frame",
    name: "Sofa Frame",
    what: "The rigid internal structure a sofa's cushions and upholstery are built around.",
    why: "It has to hold the sofa's shape and bear repeated sitting weight without sagging or collapsing over years of daily use.",
    has: ["wood"],
  },
  {
    slug: "upholstery",
    name: "Upholstery",
    what: "The fabric or leather covering stretched over a sofa's frame and cushions.",
    why: "It protects the padding underneath from wear and dirt while giving the sofa a surface that's comfortable to touch and easy to clean.",
    has: ["fabric"],
  },
  {
    slug: "screen",
    name: "Screen",
    what: "The panel that displays the image, made of many individually lit or shuttered pixels.",
    why: "It's what actually renders the picture — the rest of the television exists only to receive, process, and power what appears here.",
    has: ["pixels", "glass"],
  },
  {
    slug: "speaker",
    name: "Speaker",
    what: "A component that converts electrical signal into sound.",
    why: "A moving picture without sound loses dialogue, music, and cues. The speaker is what makes the television carry more than half the story.",
    has: ["diaphragm", "magnet"],
  },
  {
    slug: "remote",
    name: "Remote",
    what: "A handheld wireless control for the television.",
    why: "Getting up to change every channel or adjust the volume would defeat the point of relaxing in front of the screen. The remote lets that happen from the seat.",
    has: ["infrared LED", "buttons"],
  },
  {
    slug: "bookshelf-shelves",
    name: "Bookshelf Shelves",
    what: "The horizontal boards a bookshelf is built from, spaced to hold books upright.",
    why: "Books need a flat, level surface to stand on so their spines stay visible instead of toppling sideways into a pile.",
    has: ["wood"],
  },
  {
    slug: "bookshelf-frame",
    name: "Bookshelf Frame",
    what: "The vertical sides and back that hold a bookshelf's boards in place and bear their weight.",
    why: "Without a rigid frame around them, the shelf boards would flex, tip, or spread apart under the weight of the books stacked on them.",
    has: ["wood"],
  },
  {
    slug: "fabric",
    name: "Fabric",
    what: "Woven or knit cloth made from interlocking fibers.",
    why: "Loose fibers on their own are just dust or thread. Weaving or knitting them together creates a flexible sheet that's both durable and easy to shape around objects.",
    has: [],
  },
  {
    slug: "stitching",
    name: "Stitching",
    what: "Thread sewn through fabric in a repeating pattern to join two edges together.",
    why: "Fabric alone doesn't hold a shape. Stitching is what turns loose panels of cloth into a fitted, structural cover that stays together under regular use.",
    has: [],
  },
  {
    slug: "steel",
    name: "Steel",
    what: "An alloy of iron with a small, controlled amount of carbon.",
    why: "Pure iron is too soft to hold an edge and too prone to rust. Adding carbon and hardening it lets steel stay sharp, rigid, or springy far longer than iron alone.",
    has: [],
  },
  {
    slug: "bevel",
    name: "Bevel",
    what: "The angled, ground surface where the two faces of a blade meet to form its edge.",
    why: "A steep bevel makes a strong but blunt edge; a shallow one makes a sharp but fragile edge. The bevel angle is what tunes that trade-off.",
    has: [],
  },
  {
    slug: "rivets",
    name: "Rivets",
    what: "Short metal pins that clamp two flat parts together through matching holes.",
    why: "Glue can fail under repeated flexing and screws can back out over time. A rivet's deformed head can't loosen on its own, which matters on a part gripped and twisted constantly.",
    has: [],
  },
  {
    slug: "cutting-angle",
    name: "Cutting Angle",
    what: "The angle at which a blade's two ground faces meet at its very tip.",
    why: "It's the single measurement that determines whether an edge is durable and blunt or sharp and fragile — everything else about sharpening is aimed at controlling this number.",
    has: [],
  },
  {
    slug: "burr",
    name: "Burr",
    what: "A thin, rolled-over ridge of metal left standing at the edge after grinding.",
    why: "Sharpening always raises a burr first. Knowing it's there and removing it is what separates a merely-ground edge from a genuinely sharp one.",
    has: [],
  },
  {
    slug: "gas-jet",
    name: "Gas Jet",
    what: "A small nozzle that releases pressurized gas in a controlled, even ring.",
    why: "An open, unrestricted gas line would flare unevenly. The jet's fixed opening shapes the gas into a stable ring of flame instead.",
    has: [],
  },
  {
    slug: "igniter",
    name: "Igniter",
    what: "A spark-generating component that lights gas as it's released.",
    why: "Gas alone doesn't combust on its own — something has to supply the first spark. Doing that automatically means never needing a match to start cooking.",
    has: [],
  },
  {
    slug: "shaft",
    name: "Shaft",
    what: "The rod connecting a knob a person turns to the valve or switch it controls.",
    why: "It transmits the twisting motion from outside the appliance to the mechanism actually doing the regulating, without exposing that mechanism to the user's hand.",
    has: [],
  },
  {
    slug: "detents",
    name: "Detents",
    what: "Small mechanical stops inside a knob that create resistance at set points as it turns.",
    why: "They let a person feel and repeat an exact setting, like medium heat, by touch alone, without having to look down and read a dial.",
    has: [],
  },
  {
    slug: "ceramic",
    name: "Ceramic",
    what: "A hard, heat-resistant material made by firing mineral compounds at high temperature.",
    why: "It tolerates direct, repeated high heat without warping, cracking from thermal shock, or reacting with food or water — something most metals and all plastics can't do.",
    has: [],
  },
  {
    slug: "grate",
    name: "Grate",
    what: "A metal framework that sits over a burner to hold pots above the flame.",
    why: "A pot needs to sit above the flame with airflow underneath it, not directly on top of the burner smothering the fire.",
    has: [],
  },
  {
    slug: "motor",
    name: "Motor",
    what: "A component that converts electricity into rotating mechanical motion.",
    why: "Compressing gas takes continuous mechanical work. The motor is what supplies that work, drawing it straight from the wall outlet's electricity.",
    has: [],
  },
  {
    slug: "refrigerant",
    name: "Refrigerant",
    what: "A chemical that absorbs heat as it evaporates and releases it as it condenses.",
    why: "It's the substance actually carrying heat out of the cabinet. The compressor just cycles it between those two states over and over.",
    has: [],
  },
  {
    slug: "insulation",
    name: "Insulation",
    what: "A foam or fiber material packed between a cabinet's inner and outer walls.",
    why: "Trapped pockets of still air conduct heat far more slowly than the metal walls around them, so a layer of insulation is what actually keeps outside heat from reaching the cold interior.",
    has: [],
  },
  {
    slug: "glass",
    name: "Glass",
    what: "A hard, transparent material made by melting and rapidly cooling silica-based minerals.",
    why: "Its transparency lets what's behind it stay visible without opening or exposing it, and its hardness resists most everyday scratches and spills.",
    has: [],
  },
  {
    slug: "wire",
    name: "Wire",
    what: "Metal drawn out into a thin, flexible strand.",
    why: "Shaped into a grid or coil it holds weight or carries current like a solid piece would, while staying light and letting air or light pass through the gaps.",
    has: [],
  },
  {
    slug: "wood",
    name: "Wood",
    what: "The fibrous structural material from a tree's trunk and branches, cut and dried for building.",
    why: "It's strong along its grain relative to its weight, easy to shape with hand tools, and doesn't conduct heat or cold the way metal does.",
    has: [],
  },
  {
    slug: "down",
    name: "Down",
    what: "The soft, fine layer of feathers found underneath a bird's outer feathers.",
    why: "Its clustered, branching structure traps air in tiny pockets, which is what actually insulates and cushions — the down itself is just the frame holding that air in place.",
    has: [],
  },
  {
    slug: "fiberfill",
    name: "Fiberfill",
    what: "Synthetic fibers, often polyester, crimped and clustered to mimic down.",
    why: "It gives similar loft and cushioning to down without the cost or allergy risk, though it compresses and loses its shape faster over repeated use.",
    has: [],
  },
  {
    slug: "zipper",
    name: "Zipper",
    what: "Two rows of interlocking teeth drawn together by a sliding pull.",
    why: "It lets a case be opened fully to remove and wash what's inside, then resealed just as fast — something permanent stitching alone can't do reversibly.",
    has: [],
  },
  {
    slug: "hinges",
    name: "Hinges",
    what: "A jointed metal fitting that lets one panel pivot against a fixed frame.",
    why: "Without a pivot point, a panel would have to be lifted fully in and out rather than swinging open and closed in place.",
    has: [],
  },
  {
    slug: "filament",
    name: "Filament",
    what: "A thin wire, usually tungsten, that glows white-hot when current passes through it.",
    why: "Resistance in the thin wire converts electrical energy directly into heat and light. Tungsten is used because it can reach that heat without melting.",
    has: [],
  },
  {
    slug: "contacts",
    name: "Contacts",
    what: "Two conductive metal points that touch to complete a circuit or separate to break it.",
    why: "Physically joining or separating two contacts is the simplest, most reliable way to start and stop the flow of electricity on demand.",
    has: [],
  },
  {
    slug: "spring",
    name: "Spring",
    what: "A coiled piece of metal that stores energy when bent and releases it to snap back to shape.",
    why: "It gives a switch or button a decisive, self-resetting click, so it returns to its resting position on its own instead of staying wherever it was pushed.",
    has: [],
  },
  {
    slug: "flush-valve",
    name: "Flush Valve",
    what: "A valve at the bottom of a toilet tank that opens to release its stored water into the bowl at once.",
    why: "The tank's whole volume of water has to release almost instantly for the flush to have enough force to clear the bowl in a single motion.",
    has: [],
  },
  {
    slug: "nozzles",
    name: "Nozzles",
    what: "Small individual openings that each shape water into a single narrow stream.",
    why: "Many small streams cover far more surface area evenly than one single wide stream would at the same water pressure.",
    has: [],
  },
  {
    slug: "trap",
    name: "Trap",
    what: "A curved section of pipe just below a drain that stays filled with water.",
    why: "That trapped water blocks sewer gas from rising back up through the drain, the same job a toilet bowl's standing water does for the room it sits in.",
    has: [],
  },
  {
    slug: "valve",
    name: "Valve",
    what: "A mechanism inside a faucet that opens or restricts the path water flows through.",
    why: "Turning a handle needs to translate into more or less water actually passing through. The valve is the part doing that restriction.",
    has: [],
  },
  {
    slug: "pixels",
    name: "Pixels",
    what: "The smallest individually controllable points of light that together form a displayed image.",
    why: "No single light source could reproduce a detailed picture. Splitting the image into thousands of tiny, independently lit points is what makes arbitrary images possible at all.",
    has: [],
  },
  {
    slug: "diaphragm",
    name: "Diaphragm",
    what: "A thin, flexible cone or membrane that vibrates to push air and create sound waves.",
    why: "Sound is just moving air. The diaphragm is the physical surface that actually does the moving, translating electrical signal into audible pressure waves.",
    has: [],
  },
  {
    slug: "magnet",
    name: "Magnet",
    what: "A component that creates a magnetic field, used in a speaker to drive the diaphragm's motion.",
    why: "A coil carrying varying current sits next to the magnet and gets pushed and pulled as that current changes, and that motion is what drives the diaphragm.",
    has: [],
  },
  {
    slug: "infrared-led",
    name: "Infrared LED",
    what: "A small component that emits invisible infrared light in coded pulses.",
    why: "It's the actual signal carrier — the television reads the pattern of pulses as a specific command, all without any wired connection between the two.",
    has: [],
  },
  {
    slug: "buttons",
    name: "Buttons",
    what: "Physical switches on a remote's surface, each mapped to a specific command.",
    why: "They give a fast, tactile way to select a command by feel, without looking away from the screen to find it.",
    has: [],
  },
  {
    slug: "carbon",
    name: "Carbon",
    what: "An atom with four bonding sites, able to link to other carbon atoms in long chains and rings.",
    why: "That four-way bonding capacity is what lets it form the long, stable backbones every organic polymer chain is built on — nothing else bonds as flexibly or as strongly with itself.",
    has: [],
  },
  {
    slug: "hydrogen",
    name: "Hydrogen",
    what: "The smallest, lightest atom, usually bonded along a polymer's carbon backbone.",
    why: "It fills the remaining bonding sites along the chain, and how many attach where is part of what shapes the chain's flexibility and weight.",
    has: [],
  },
  {
    slug: "oxygen",
    name: "Oxygen",
    what: "An atom that bonds readily with carbon and hydrogen, often bridging or capping a chain.",
    why: "Placing oxygen at specific points along the backbone creates reactive sites chemists use to control how and where chains link, stretch, or eventually break down.",
    has: [],
  },
];

export function getArtifact(slug: string): Artifact | undefined {
  return artifacts.find((a) => a.slug === slug);
}

/** Artifacts with no other artifact listing them under "has" — the top level. */
export function getRoots(): Artifact[] {
  const childSlugs = new Set(
    artifacts.flatMap((a) => a.has.map((name) => slugify(name)))
  );
  return artifacts.filter((a) => !childSlugs.has(a.slug));
}

/** The artifact that lists this slug under "has", if any. */
export function getParent(slug: string): Artifact | undefined {
  return artifacts.find((a) => a.has.some((name) => slugify(name) === slug));
}

/** Root-to-self chain of artifacts, for breadcrumbs. */
export function getAncestry(slug: string): Artifact[] {
  const chain: Artifact[] = [];
  let current = getArtifact(slug);
  const seen = new Set<string>();
  while (current && !seen.has(current.slug)) {
    chain.unshift(current);
    seen.add(current.slug);
    current = getParent(current.slug);
  }
  return chain;
}

export function getChildSlug(name: string): string {
  return slugify(name);
}
